// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: carbon_credits.sql

package database

import (
	"context"
	"database/sql"
)

const countCarbonCredits = `-- name: CountCarbonCredits :one
SELECT COUNT(*) FROM carbon_credits
`

func (q *Queries) CountCarbonCredits(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countCarbonCreditsStmt, countCarbonCredits)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCarbonCredit = `-- name: CreateCarbonCredit :one
INSERT INTO carbon_credits (
    project_name,
    credit_type,
    price_per_ton,
    available_tons,
    vintage_year,
    verification_standard,
    location,
    project_description
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, project_name, credit_type, price_per_ton, available_tons, vintage_year, verification_standard, location, project_description, created_at
`

type CreateCarbonCreditParams struct {
	ProjectName          string         `json:"project_name"`
	CreditType           sql.NullString `json:"credit_type"`
	PricePerTon          float64        `json:"price_per_ton"`
	AvailableTons        float64        `json:"available_tons"`
	VintageYear          sql.NullInt64  `json:"vintage_year"`
	VerificationStandard sql.NullString `json:"verification_standard"`
	Location             sql.NullString `json:"location"`
	ProjectDescription   sql.NullString `json:"project_description"`
}

func (q *Queries) CreateCarbonCredit(ctx context.Context, arg CreateCarbonCreditParams) (CarbonCredit, error) {
	row := q.queryRow(ctx, q.createCarbonCreditStmt, createCarbonCredit,
		arg.ProjectName,
		arg.CreditType,
		arg.PricePerTon,
		arg.AvailableTons,
		arg.VintageYear,
		arg.VerificationStandard,
		arg.Location,
		arg.ProjectDescription,
	)
	var i CarbonCredit
	err := row.Scan(
		&i.ID,
		&i.ProjectName,
		&i.CreditType,
		&i.PricePerTon,
		&i.AvailableTons,
		&i.VintageYear,
		&i.VerificationStandard,
		&i.Location,
		&i.ProjectDescription,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCarbonCredit = `-- name: DeleteCarbonCredit :exec
DELETE FROM carbon_credits
WHERE id = ?
`

func (q *Queries) DeleteCarbonCredit(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteCarbonCreditStmt, deleteCarbonCredit, id)
	return err
}

const getCarbonCredit = `-- name: GetCarbonCredit :one
SELECT id, project_name, credit_type, price_per_ton, available_tons, vintage_year, verification_standard, location, project_description, created_at FROM carbon_credits
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetCarbonCredit(ctx context.Context, id int64) (CarbonCredit, error) {
	row := q.queryRow(ctx, q.getCarbonCreditStmt, getCarbonCredit, id)
	var i CarbonCredit
	err := row.Scan(
		&i.ID,
		&i.ProjectName,
		&i.CreditType,
		&i.PricePerTon,
		&i.AvailableTons,
		&i.VintageYear,
		&i.VerificationStandard,
		&i.Location,
		&i.ProjectDescription,
		&i.CreatedAt,
	)
	return i, err
}

const listCarbonCredits = `-- name: ListCarbonCredits :many
SELECT id, project_name, credit_type, price_per_ton, available_tons, vintage_year, verification_standard, location, project_description, created_at FROM carbon_credits
ORDER BY project_name
LIMIT ? OFFSET ?
`

type ListCarbonCreditsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListCarbonCredits(ctx context.Context, arg ListCarbonCreditsParams) ([]CarbonCredit, error) {
	rows, err := q.query(ctx, q.listCarbonCreditsStmt, listCarbonCredits, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CarbonCredit{}
	for rows.Next() {
		var i CarbonCredit
		if err := rows.Scan(
			&i.ID,
			&i.ProjectName,
			&i.CreditType,
			&i.PricePerTon,
			&i.AvailableTons,
			&i.VintageYear,
			&i.VerificationStandard,
			&i.Location,
			&i.ProjectDescription,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCarbonCredit = `-- name: UpdateCarbonCredit :one
UPDATE carbon_credits
SET
    project_name = COALESCE(?, project_name),
    credit_type = COALESCE(?, credit_type),
    price_per_ton = COALESCE(?, price_per_ton),
    available_tons = COALESCE(?, available_tons),
    vintage_year = COALESCE(?, vintage_year),
    verification_standard = COALESCE(?, verification_standard),
    location = COALESCE(?, location),
    project_description = COALESCE(?, project_description)
WHERE id = ?
RETURNING id, project_name, credit_type, price_per_ton, available_tons, vintage_year, verification_standard, location, project_description, created_at
`

type UpdateCarbonCreditParams struct {
	ProjectName          string         `json:"project_name"`
	CreditType           sql.NullString `json:"credit_type"`
	PricePerTon          float64        `json:"price_per_ton"`
	AvailableTons        float64        `json:"available_tons"`
	VintageYear          sql.NullInt64  `json:"vintage_year"`
	VerificationStandard sql.NullString `json:"verification_standard"`
	Location             sql.NullString `json:"location"`
	ProjectDescription   sql.NullString `json:"project_description"`
	ID                   int64          `json:"id"`
}

func (q *Queries) UpdateCarbonCredit(ctx context.Context, arg UpdateCarbonCreditParams) (CarbonCredit, error) {
	row := q.queryRow(ctx, q.updateCarbonCreditStmt, updateCarbonCredit,
		arg.ProjectName,
		arg.CreditType,
		arg.PricePerTon,
		arg.AvailableTons,
		arg.VintageYear,
		arg.VerificationStandard,
		arg.Location,
		arg.ProjectDescription,
		arg.ID,
	)
	var i CarbonCredit
	err := row.Scan(
		&i.ID,
		&i.ProjectName,
		&i.CreditType,
		&i.PricePerTon,
		&i.AvailableTons,
		&i.VintageYear,
		&i.VerificationStandard,
		&i.Location,
		&i.ProjectDescription,
		&i.CreatedAt,
	)
	return i, err
}
