// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package database

import (
	"context"
	"database/sql"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (user_identifier, action, entity_type, icon_type)
VALUES (?, ?, ?, ?)
RETURNING id, user_identifier, "action", entity_type, icon_type, created_at
`

type CreateAuditLogParams struct {
	UserIdentifier string `json:"user_identifier"`
	Action         string `json:"action"`
	EntityType     string `json:"entity_type"`
	IconType       string `json:"icon_type"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.queryRow(ctx, q.createAuditLogStmt, createAuditLog,
		arg.UserIdentifier,
		arg.Action,
		arg.EntityType,
		arg.IconType,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserIdentifier,
		&i.Action,
		&i.EntityType,
		&i.IconType,
		&i.CreatedAt,
	)
	return i, err
}

const getDashboardStats = `-- name: GetDashboardStats :one
SELECT 
    (SELECT COUNT(*) FROM data_centers) as active_sites,
    (SELECT COUNT(*) FROM audit_logs) as total_activities, -- specialized query might be better but this works for now
    -- Compliance % is dynamically calculated in code usually, but we can grab raw counts
    (SELECT COUNT(*) FROM feasibility_assessments WHERE status = 'completed') as completed_assessments
`

type GetDashboardStatsRow struct {
	ActiveSites          int64 `json:"active_sites"`
	TotalActivities      int64 `json:"total_activities"`
	CompletedAssessments int64 `json:"completed_assessments"`
}

func (q *Queries) GetDashboardStats(ctx context.Context) (GetDashboardStatsRow, error) {
	row := q.queryRow(ctx, q.getDashboardStatsStmt, getDashboardStats)
	var i GetDashboardStatsRow
	err := row.Scan(&i.ActiveSites, &i.TotalActivities, &i.CompletedAssessments)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, first_name, last_name, created_at, notify_assessment_complete, notify_regulatory_updates, api_key_live, api_key_test FROM users
WHERE email = ? LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, email string) (User, error) {
	row := q.queryRow(ctx, q.getUserStmt, getUser, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.NotifyAssessmentComplete,
		&i.NotifyRegulatoryUpdates,
		&i.ApiKeyLive,
		&i.ApiKeyTest,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, user_identifier, "action", entity_type, icon_type, created_at FROM audit_logs
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListAuditLogsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.query(ctx, q.listAuditLogsStmt, listAuditLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserIdentifier,
			&i.Action,
			&i.EntityType,
			&i.IconType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET first_name = ?,
    last_name = ?,
    notify_assessment_complete = ?,
    notify_regulatory_updates = ?
WHERE email = ?
RETURNING id, email, first_name, last_name, created_at, notify_assessment_complete, notify_regulatory_updates, api_key_live, api_key_test
`

type UpdateUserParams struct {
	FirstName                string       `json:"first_name"`
	LastName                 string       `json:"last_name"`
	NotifyAssessmentComplete sql.NullBool `json:"notify_assessment_complete"`
	NotifyRegulatoryUpdates  sql.NullBool `json:"notify_regulatory_updates"`
	Email                    string       `json:"email"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.queryRow(ctx, q.updateUserStmt, updateUser,
		arg.FirstName,
		arg.LastName,
		arg.NotifyAssessmentComplete,
		arg.NotifyRegulatoryUpdates,
		arg.Email,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.NotifyAssessmentComplete,
		&i.NotifyRegulatoryUpdates,
		&i.ApiKeyLive,
		&i.ApiKeyTest,
	)
	return i, err
}
