// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: data_centers.sql

package database

import (
	"context"
	"database/sql"
)

const countDataCenters = `-- name: CountDataCenters :one
SELECT COUNT(*) FROM data_centers
`

func (q *Queries) CountDataCenters(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countDataCentersStmt, countDataCenters)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDataCenter = `-- name: CreateDataCenter :one
INSERT INTO data_centers (
    name,
    location_lat,
    location_lng,
    address,
    dc_type,
    total_it_load_kw,
    pue,
    utilization_percent,
    cooling_type,
    energy_source,
    renewable_percent,
    electricity_cost_kwh,
    operating_hours_year,
    heat_recovery_enabled
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, location_lat, location_lng, address, dc_type, total_it_load_kw, pue, utilization_percent, cooling_type, energy_source, renewable_percent, electricity_cost_kwh, operating_hours_year, heat_recovery_enabled, created_at
`

type CreateDataCenterParams struct {
	Name                string          `json:"name"`
	LocationLat         float64         `json:"location_lat"`
	LocationLng         float64         `json:"location_lng"`
	Address             sql.NullString  `json:"address"`
	DcType              sql.NullString  `json:"dc_type"`
	TotalItLoadKw       float64         `json:"total_it_load_kw"`
	Pue                 sql.NullFloat64 `json:"pue"`
	UtilizationPercent  sql.NullFloat64 `json:"utilization_percent"`
	CoolingType         sql.NullString  `json:"cooling_type"`
	EnergySource        sql.NullString  `json:"energy_source"`
	RenewablePercent    sql.NullFloat64 `json:"renewable_percent"`
	ElectricityCostKwh  sql.NullFloat64 `json:"electricity_cost_kwh"`
	OperatingHoursYear  sql.NullInt64   `json:"operating_hours_year"`
	HeatRecoveryEnabled sql.NullInt64   `json:"heat_recovery_enabled"`
}

func (q *Queries) CreateDataCenter(ctx context.Context, arg CreateDataCenterParams) (DataCenter, error) {
	row := q.queryRow(ctx, q.createDataCenterStmt, createDataCenter,
		arg.Name,
		arg.LocationLat,
		arg.LocationLng,
		arg.Address,
		arg.DcType,
		arg.TotalItLoadKw,
		arg.Pue,
		arg.UtilizationPercent,
		arg.CoolingType,
		arg.EnergySource,
		arg.RenewablePercent,
		arg.ElectricityCostKwh,
		arg.OperatingHoursYear,
		arg.HeatRecoveryEnabled,
	)
	var i DataCenter
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LocationLat,
		&i.LocationLng,
		&i.Address,
		&i.DcType,
		&i.TotalItLoadKw,
		&i.Pue,
		&i.UtilizationPercent,
		&i.CoolingType,
		&i.EnergySource,
		&i.RenewablePercent,
		&i.ElectricityCostKwh,
		&i.OperatingHoursYear,
		&i.HeatRecoveryEnabled,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDataCenter = `-- name: DeleteDataCenter :exec
DELETE FROM data_centers
WHERE id = ?
`

func (q *Queries) DeleteDataCenter(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteDataCenterStmt, deleteDataCenter, id)
	return err
}

const getDataCenter = `-- name: GetDataCenter :one
SELECT id, name, location_lat, location_lng, address, dc_type, total_it_load_kw, pue, utilization_percent, cooling_type, energy_source, renewable_percent, electricity_cost_kwh, operating_hours_year, heat_recovery_enabled, created_at FROM data_centers
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetDataCenter(ctx context.Context, id int64) (DataCenter, error) {
	row := q.queryRow(ctx, q.getDataCenterStmt, getDataCenter, id)
	var i DataCenter
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LocationLat,
		&i.LocationLng,
		&i.Address,
		&i.DcType,
		&i.TotalItLoadKw,
		&i.Pue,
		&i.UtilizationPercent,
		&i.CoolingType,
		&i.EnergySource,
		&i.RenewablePercent,
		&i.ElectricityCostKwh,
		&i.OperatingHoursYear,
		&i.HeatRecoveryEnabled,
		&i.CreatedAt,
	)
	return i, err
}

const listDataCenters = `-- name: ListDataCenters :many
SELECT id, name, location_lat, location_lng, address, dc_type, total_it_load_kw, pue, utilization_percent, cooling_type, energy_source, renewable_percent, electricity_cost_kwh, operating_hours_year, heat_recovery_enabled, created_at FROM data_centers
ORDER BY name
LIMIT ? OFFSET ?
`

type ListDataCentersParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListDataCenters(ctx context.Context, arg ListDataCentersParams) ([]DataCenter, error) {
	rows, err := q.query(ctx, q.listDataCentersStmt, listDataCenters, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DataCenter{}
	for rows.Next() {
		var i DataCenter
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LocationLat,
			&i.LocationLng,
			&i.Address,
			&i.DcType,
			&i.TotalItLoadKw,
			&i.Pue,
			&i.UtilizationPercent,
			&i.CoolingType,
			&i.EnergySource,
			&i.RenewablePercent,
			&i.ElectricityCostKwh,
			&i.OperatingHoursYear,
			&i.HeatRecoveryEnabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDataCenter = `-- name: UpdateDataCenter :one
UPDATE data_centers
SET
    name = COALESCE(?, name),
    location_lat = COALESCE(?, location_lat),
    location_lng = COALESCE(?, location_lng),
    address = COALESCE(?, address),
    dc_type = COALESCE(?, dc_type),
    total_it_load_kw = COALESCE(?, total_it_load_kw),
    pue = COALESCE(?, pue),
    utilization_percent = COALESCE(?, utilization_percent),
    cooling_type = COALESCE(?, cooling_type),
    energy_source = COALESCE(?, energy_source),
    renewable_percent = COALESCE(?, renewable_percent),
    electricity_cost_kwh = COALESCE(?, electricity_cost_kwh),
    operating_hours_year = COALESCE(?, operating_hours_year),
    heat_recovery_enabled = COALESCE(?, heat_recovery_enabled)
WHERE id = ?
RETURNING id, name, location_lat, location_lng, address, dc_type, total_it_load_kw, pue, utilization_percent, cooling_type, energy_source, renewable_percent, electricity_cost_kwh, operating_hours_year, heat_recovery_enabled, created_at
`

type UpdateDataCenterParams struct {
	Name                string          `json:"name"`
	LocationLat         float64         `json:"location_lat"`
	LocationLng         float64         `json:"location_lng"`
	Address             sql.NullString  `json:"address"`
	DcType              sql.NullString  `json:"dc_type"`
	TotalItLoadKw       float64         `json:"total_it_load_kw"`
	Pue                 sql.NullFloat64 `json:"pue"`
	UtilizationPercent  sql.NullFloat64 `json:"utilization_percent"`
	CoolingType         sql.NullString  `json:"cooling_type"`
	EnergySource        sql.NullString  `json:"energy_source"`
	RenewablePercent    sql.NullFloat64 `json:"renewable_percent"`
	ElectricityCostKwh  sql.NullFloat64 `json:"electricity_cost_kwh"`
	OperatingHoursYear  sql.NullInt64   `json:"operating_hours_year"`
	HeatRecoveryEnabled sql.NullInt64   `json:"heat_recovery_enabled"`
	ID                  int64           `json:"id"`
}

func (q *Queries) UpdateDataCenter(ctx context.Context, arg UpdateDataCenterParams) (DataCenter, error) {
	row := q.queryRow(ctx, q.updateDataCenterStmt, updateDataCenter,
		arg.Name,
		arg.LocationLat,
		arg.LocationLng,
		arg.Address,
		arg.DcType,
		arg.TotalItLoadKw,
		arg.Pue,
		arg.UtilizationPercent,
		arg.CoolingType,
		arg.EnergySource,
		arg.RenewablePercent,
		arg.ElectricityCostKwh,
		arg.OperatingHoursYear,
		arg.HeatRecoveryEnabled,
		arg.ID,
	)
	var i DataCenter
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LocationLat,
		&i.LocationLng,
		&i.Address,
		&i.DcType,
		&i.TotalItLoadKw,
		&i.Pue,
		&i.UtilizationPercent,
		&i.CoolingType,
		&i.EnergySource,
		&i.RenewablePercent,
		&i.ElectricityCostKwh,
		&i.OperatingHoursYear,
		&i.HeatRecoveryEnabled,
		&i.CreatedAt,
	)
	return i, err
}
