// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.countCarbonCreditsStmt, err = db.PrepareContext(ctx, countCarbonCredits); err != nil {
		return nil, fmt.Errorf("error preparing query CountCarbonCredits: %w", err)
	}
	if q.countDataCentersStmt, err = db.PrepareContext(ctx, countDataCenters); err != nil {
		return nil, fmt.Errorf("error preparing query CountDataCenters: %w", err)
	}
	if q.countDemandSitesStmt, err = db.PrepareContext(ctx, countDemandSites); err != nil {
		return nil, fmt.Errorf("error preparing query CountDemandSites: %w", err)
	}
	if q.countHeatCentersStmt, err = db.PrepareContext(ctx, countHeatCenters); err != nil {
		return nil, fmt.Errorf("error preparing query CountHeatCenters: %w", err)
	}
	if q.countHeatSinksStmt, err = db.PrepareContext(ctx, countHeatSinks); err != nil {
		return nil, fmt.Errorf("error preparing query CountHeatSinks: %w", err)
	}
	if q.countPredictionResultsStmt, err = db.PrepareContext(ctx, countPredictionResults); err != nil {
		return nil, fmt.Errorf("error preparing query CountPredictionResults: %w", err)
	}
	if q.countRoutesStmt, err = db.PrepareContext(ctx, countRoutes); err != nil {
		return nil, fmt.Errorf("error preparing query CountRoutes: %w", err)
	}
	if q.createCarbonCreditStmt, err = db.PrepareContext(ctx, createCarbonCredit); err != nil {
		return nil, fmt.Errorf("error preparing query CreateCarbonCredit: %w", err)
	}
	if q.createDataCenterStmt, err = db.PrepareContext(ctx, createDataCenter); err != nil {
		return nil, fmt.Errorf("error preparing query CreateDataCenter: %w", err)
	}
	if q.createDemandSiteStmt, err = db.PrepareContext(ctx, createDemandSite); err != nil {
		return nil, fmt.Errorf("error preparing query CreateDemandSite: %w", err)
	}
	if q.createHeatCenterStmt, err = db.PrepareContext(ctx, createHeatCenter); err != nil {
		return nil, fmt.Errorf("error preparing query CreateHeatCenter: %w", err)
	}
	if q.createHeatSinkStmt, err = db.PrepareContext(ctx, createHeatSink); err != nil {
		return nil, fmt.Errorf("error preparing query CreateHeatSink: %w", err)
	}
	if q.createPredictionResultStmt, err = db.PrepareContext(ctx, createPredictionResult); err != nil {
		return nil, fmt.Errorf("error preparing query CreatePredictionResult: %w", err)
	}
	if q.createRouteStmt, err = db.PrepareContext(ctx, createRoute); err != nil {
		return nil, fmt.Errorf("error preparing query CreateRoute: %w", err)
	}
	if q.deleteCarbonCreditStmt, err = db.PrepareContext(ctx, deleteCarbonCredit); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteCarbonCredit: %w", err)
	}
	if q.deleteDataCenterStmt, err = db.PrepareContext(ctx, deleteDataCenter); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteDataCenter: %w", err)
	}
	if q.deleteDemandSiteStmt, err = db.PrepareContext(ctx, deleteDemandSite); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteDemandSite: %w", err)
	}
	if q.deleteHeatCenterStmt, err = db.PrepareContext(ctx, deleteHeatCenter); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteHeatCenter: %w", err)
	}
	if q.deleteHeatSinkStmt, err = db.PrepareContext(ctx, deleteHeatSink); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteHeatSink: %w", err)
	}
	if q.deletePredictionResultStmt, err = db.PrepareContext(ctx, deletePredictionResult); err != nil {
		return nil, fmt.Errorf("error preparing query DeletePredictionResult: %w", err)
	}
	if q.deleteRouteStmt, err = db.PrepareContext(ctx, deleteRoute); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteRoute: %w", err)
	}
	if q.getAnalyticsSummaryStmt, err = db.PrepareContext(ctx, getAnalyticsSummary); err != nil {
		return nil, fmt.Errorf("error preparing query GetAnalyticsSummary: %w", err)
	}
	if q.getCarbonCreditStmt, err = db.PrepareContext(ctx, getCarbonCredit); err != nil {
		return nil, fmt.Errorf("error preparing query GetCarbonCredit: %w", err)
	}
	if q.getDataCenterStmt, err = db.PrepareContext(ctx, getDataCenter); err != nil {
		return nil, fmt.Errorf("error preparing query GetDataCenter: %w", err)
	}
	if q.getDemandSiteStmt, err = db.PrepareContext(ctx, getDemandSite); err != nil {
		return nil, fmt.Errorf("error preparing query GetDemandSite: %w", err)
	}
	if q.getHeatCenterStmt, err = db.PrepareContext(ctx, getHeatCenter); err != nil {
		return nil, fmt.Errorf("error preparing query GetHeatCenter: %w", err)
	}
	if q.getHeatSinkStmt, err = db.PrepareContext(ctx, getHeatSink); err != nil {
		return nil, fmt.Errorf("error preparing query GetHeatSink: %w", err)
	}
	if q.getPredictionResultStmt, err = db.PrepareContext(ctx, getPredictionResult); err != nil {
		return nil, fmt.Errorf("error preparing query GetPredictionResult: %w", err)
	}
	if q.getPredictionResultsByDataCenterStmt, err = db.PrepareContext(ctx, getPredictionResultsByDataCenter); err != nil {
		return nil, fmt.Errorf("error preparing query GetPredictionResultsByDataCenter: %w", err)
	}
	if q.getPredictionResultsByScenarioStmt, err = db.PrepareContext(ctx, getPredictionResultsByScenario); err != nil {
		return nil, fmt.Errorf("error preparing query GetPredictionResultsByScenario: %w", err)
	}
	if q.getRouteStmt, err = db.PrepareContext(ctx, getRoute); err != nil {
		return nil, fmt.Errorf("error preparing query GetRoute: %w", err)
	}
	if q.listCarbonCreditsStmt, err = db.PrepareContext(ctx, listCarbonCredits); err != nil {
		return nil, fmt.Errorf("error preparing query ListCarbonCredits: %w", err)
	}
	if q.listDataCentersStmt, err = db.PrepareContext(ctx, listDataCenters); err != nil {
		return nil, fmt.Errorf("error preparing query ListDataCenters: %w", err)
	}
	if q.listDemandSitesStmt, err = db.PrepareContext(ctx, listDemandSites); err != nil {
		return nil, fmt.Errorf("error preparing query ListDemandSites: %w", err)
	}
	if q.listHeatCentersStmt, err = db.PrepareContext(ctx, listHeatCenters); err != nil {
		return nil, fmt.Errorf("error preparing query ListHeatCenters: %w", err)
	}
	if q.listHeatSinksStmt, err = db.PrepareContext(ctx, listHeatSinks); err != nil {
		return nil, fmt.Errorf("error preparing query ListHeatSinks: %w", err)
	}
	if q.listPredictionResultsStmt, err = db.PrepareContext(ctx, listPredictionResults); err != nil {
		return nil, fmt.Errorf("error preparing query ListPredictionResults: %w", err)
	}
	if q.listRoutesStmt, err = db.PrepareContext(ctx, listRoutes); err != nil {
		return nil, fmt.Errorf("error preparing query ListRoutes: %w", err)
	}
	if q.updateCarbonCreditStmt, err = db.PrepareContext(ctx, updateCarbonCredit); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateCarbonCredit: %w", err)
	}
	if q.updateDataCenterStmt, err = db.PrepareContext(ctx, updateDataCenter); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateDataCenter: %w", err)
	}
	if q.updateDemandSiteStmt, err = db.PrepareContext(ctx, updateDemandSite); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateDemandSite: %w", err)
	}
	if q.updateHeatCenterStmt, err = db.PrepareContext(ctx, updateHeatCenter); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateHeatCenter: %w", err)
	}
	if q.updateHeatSinkStmt, err = db.PrepareContext(ctx, updateHeatSink); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateHeatSink: %w", err)
	}
	if q.updateRouteStmt, err = db.PrepareContext(ctx, updateRoute); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateRoute: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.countCarbonCreditsStmt != nil {
		if cerr := q.countCarbonCreditsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countCarbonCreditsStmt: %w", cerr)
		}
	}
	if q.countDataCentersStmt != nil {
		if cerr := q.countDataCentersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countDataCentersStmt: %w", cerr)
		}
	}
	if q.countDemandSitesStmt != nil {
		if cerr := q.countDemandSitesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countDemandSitesStmt: %w", cerr)
		}
	}
	if q.countHeatCentersStmt != nil {
		if cerr := q.countHeatCentersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countHeatCentersStmt: %w", cerr)
		}
	}
	if q.countHeatSinksStmt != nil {
		if cerr := q.countHeatSinksStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countHeatSinksStmt: %w", cerr)
		}
	}
	if q.countPredictionResultsStmt != nil {
		if cerr := q.countPredictionResultsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countPredictionResultsStmt: %w", cerr)
		}
	}
	if q.countRoutesStmt != nil {
		if cerr := q.countRoutesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countRoutesStmt: %w", cerr)
		}
	}
	if q.createCarbonCreditStmt != nil {
		if cerr := q.createCarbonCreditStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createCarbonCreditStmt: %w", cerr)
		}
	}
	if q.createDataCenterStmt != nil {
		if cerr := q.createDataCenterStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createDataCenterStmt: %w", cerr)
		}
	}
	if q.createDemandSiteStmt != nil {
		if cerr := q.createDemandSiteStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createDemandSiteStmt: %w", cerr)
		}
	}
	if q.createHeatCenterStmt != nil {
		if cerr := q.createHeatCenterStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createHeatCenterStmt: %w", cerr)
		}
	}
	if q.createHeatSinkStmt != nil {
		if cerr := q.createHeatSinkStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createHeatSinkStmt: %w", cerr)
		}
	}
	if q.createPredictionResultStmt != nil {
		if cerr := q.createPredictionResultStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createPredictionResultStmt: %w", cerr)
		}
	}
	if q.createRouteStmt != nil {
		if cerr := q.createRouteStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createRouteStmt: %w", cerr)
		}
	}
	if q.deleteCarbonCreditStmt != nil {
		if cerr := q.deleteCarbonCreditStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteCarbonCreditStmt: %w", cerr)
		}
	}
	if q.deleteDataCenterStmt != nil {
		if cerr := q.deleteDataCenterStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteDataCenterStmt: %w", cerr)
		}
	}
	if q.deleteDemandSiteStmt != nil {
		if cerr := q.deleteDemandSiteStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteDemandSiteStmt: %w", cerr)
		}
	}
	if q.deleteHeatCenterStmt != nil {
		if cerr := q.deleteHeatCenterStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteHeatCenterStmt: %w", cerr)
		}
	}
	if q.deleteHeatSinkStmt != nil {
		if cerr := q.deleteHeatSinkStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteHeatSinkStmt: %w", cerr)
		}
	}
	if q.deletePredictionResultStmt != nil {
		if cerr := q.deletePredictionResultStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deletePredictionResultStmt: %w", cerr)
		}
	}
	if q.deleteRouteStmt != nil {
		if cerr := q.deleteRouteStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteRouteStmt: %w", cerr)
		}
	}
	if q.getAnalyticsSummaryStmt != nil {
		if cerr := q.getAnalyticsSummaryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAnalyticsSummaryStmt: %w", cerr)
		}
	}
	if q.getCarbonCreditStmt != nil {
		if cerr := q.getCarbonCreditStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCarbonCreditStmt: %w", cerr)
		}
	}
	if q.getDataCenterStmt != nil {
		if cerr := q.getDataCenterStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDataCenterStmt: %w", cerr)
		}
	}
	if q.getDemandSiteStmt != nil {
		if cerr := q.getDemandSiteStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDemandSiteStmt: %w", cerr)
		}
	}
	if q.getHeatCenterStmt != nil {
		if cerr := q.getHeatCenterStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getHeatCenterStmt: %w", cerr)
		}
	}
	if q.getHeatSinkStmt != nil {
		if cerr := q.getHeatSinkStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getHeatSinkStmt: %w", cerr)
		}
	}
	if q.getPredictionResultStmt != nil {
		if cerr := q.getPredictionResultStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPredictionResultStmt: %w", cerr)
		}
	}
	if q.getPredictionResultsByDataCenterStmt != nil {
		if cerr := q.getPredictionResultsByDataCenterStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPredictionResultsByDataCenterStmt: %w", cerr)
		}
	}
	if q.getPredictionResultsByScenarioStmt != nil {
		if cerr := q.getPredictionResultsByScenarioStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPredictionResultsByScenarioStmt: %w", cerr)
		}
	}
	if q.getRouteStmt != nil {
		if cerr := q.getRouteStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRouteStmt: %w", cerr)
		}
	}
	if q.listCarbonCreditsStmt != nil {
		if cerr := q.listCarbonCreditsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listCarbonCreditsStmt: %w", cerr)
		}
	}
	if q.listDataCentersStmt != nil {
		if cerr := q.listDataCentersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listDataCentersStmt: %w", cerr)
		}
	}
	if q.listDemandSitesStmt != nil {
		if cerr := q.listDemandSitesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listDemandSitesStmt: %w", cerr)
		}
	}
	if q.listHeatCentersStmt != nil {
		if cerr := q.listHeatCentersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listHeatCentersStmt: %w", cerr)
		}
	}
	if q.listHeatSinksStmt != nil {
		if cerr := q.listHeatSinksStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listHeatSinksStmt: %w", cerr)
		}
	}
	if q.listPredictionResultsStmt != nil {
		if cerr := q.listPredictionResultsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listPredictionResultsStmt: %w", cerr)
		}
	}
	if q.listRoutesStmt != nil {
		if cerr := q.listRoutesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listRoutesStmt: %w", cerr)
		}
	}
	if q.updateCarbonCreditStmt != nil {
		if cerr := q.updateCarbonCreditStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateCarbonCreditStmt: %w", cerr)
		}
	}
	if q.updateDataCenterStmt != nil {
		if cerr := q.updateDataCenterStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateDataCenterStmt: %w", cerr)
		}
	}
	if q.updateDemandSiteStmt != nil {
		if cerr := q.updateDemandSiteStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateDemandSiteStmt: %w", cerr)
		}
	}
	if q.updateHeatCenterStmt != nil {
		if cerr := q.updateHeatCenterStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateHeatCenterStmt: %w", cerr)
		}
	}
	if q.updateHeatSinkStmt != nil {
		if cerr := q.updateHeatSinkStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateHeatSinkStmt: %w", cerr)
		}
	}
	if q.updateRouteStmt != nil {
		if cerr := q.updateRouteStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateRouteStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                   DBTX
	tx                                   *sql.Tx
	countCarbonCreditsStmt               *sql.Stmt
	countDataCentersStmt                 *sql.Stmt
	countDemandSitesStmt                 *sql.Stmt
	countHeatCentersStmt                 *sql.Stmt
	countHeatSinksStmt                   *sql.Stmt
	countPredictionResultsStmt           *sql.Stmt
	countRoutesStmt                      *sql.Stmt
	createCarbonCreditStmt               *sql.Stmt
	createDataCenterStmt                 *sql.Stmt
	createDemandSiteStmt                 *sql.Stmt
	createHeatCenterStmt                 *sql.Stmt
	createHeatSinkStmt                   *sql.Stmt
	createPredictionResultStmt           *sql.Stmt
	createRouteStmt                      *sql.Stmt
	deleteCarbonCreditStmt               *sql.Stmt
	deleteDataCenterStmt                 *sql.Stmt
	deleteDemandSiteStmt                 *sql.Stmt
	deleteHeatCenterStmt                 *sql.Stmt
	deleteHeatSinkStmt                   *sql.Stmt
	deletePredictionResultStmt           *sql.Stmt
	deleteRouteStmt                      *sql.Stmt
	getAnalyticsSummaryStmt              *sql.Stmt
	getCarbonCreditStmt                  *sql.Stmt
	getDataCenterStmt                    *sql.Stmt
	getDemandSiteStmt                    *sql.Stmt
	getHeatCenterStmt                    *sql.Stmt
	getHeatSinkStmt                      *sql.Stmt
	getPredictionResultStmt              *sql.Stmt
	getPredictionResultsByDataCenterStmt *sql.Stmt
	getPredictionResultsByScenarioStmt   *sql.Stmt
	getRouteStmt                         *sql.Stmt
	listCarbonCreditsStmt                *sql.Stmt
	listDataCentersStmt                  *sql.Stmt
	listDemandSitesStmt                  *sql.Stmt
	listHeatCentersStmt                  *sql.Stmt
	listHeatSinksStmt                    *sql.Stmt
	listPredictionResultsStmt            *sql.Stmt
	listRoutesStmt                       *sql.Stmt
	updateCarbonCreditStmt               *sql.Stmt
	updateDataCenterStmt                 *sql.Stmt
	updateDemandSiteStmt                 *sql.Stmt
	updateHeatCenterStmt                 *sql.Stmt
	updateHeatSinkStmt                   *sql.Stmt
	updateRouteStmt                      *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                   tx,
		tx:                                   tx,
		countCarbonCreditsStmt:               q.countCarbonCreditsStmt,
		countDataCentersStmt:                 q.countDataCentersStmt,
		countDemandSitesStmt:                 q.countDemandSitesStmt,
		countHeatCentersStmt:                 q.countHeatCentersStmt,
		countHeatSinksStmt:                   q.countHeatSinksStmt,
		countPredictionResultsStmt:           q.countPredictionResultsStmt,
		countRoutesStmt:                      q.countRoutesStmt,
		createCarbonCreditStmt:               q.createCarbonCreditStmt,
		createDataCenterStmt:                 q.createDataCenterStmt,
		createDemandSiteStmt:                 q.createDemandSiteStmt,
		createHeatCenterStmt:                 q.createHeatCenterStmt,
		createHeatSinkStmt:                   q.createHeatSinkStmt,
		createPredictionResultStmt:           q.createPredictionResultStmt,
		createRouteStmt:                      q.createRouteStmt,
		deleteCarbonCreditStmt:               q.deleteCarbonCreditStmt,
		deleteDataCenterStmt:                 q.deleteDataCenterStmt,
		deleteDemandSiteStmt:                 q.deleteDemandSiteStmt,
		deleteHeatCenterStmt:                 q.deleteHeatCenterStmt,
		deleteHeatSinkStmt:                   q.deleteHeatSinkStmt,
		deletePredictionResultStmt:           q.deletePredictionResultStmt,
		deleteRouteStmt:                      q.deleteRouteStmt,
		getAnalyticsSummaryStmt:              q.getAnalyticsSummaryStmt,
		getCarbonCreditStmt:                  q.getCarbonCreditStmt,
		getDataCenterStmt:                    q.getDataCenterStmt,
		getDemandSiteStmt:                    q.getDemandSiteStmt,
		getHeatCenterStmt:                    q.getHeatCenterStmt,
		getHeatSinkStmt:                      q.getHeatSinkStmt,
		getPredictionResultStmt:              q.getPredictionResultStmt,
		getPredictionResultsByDataCenterStmt: q.getPredictionResultsByDataCenterStmt,
		getPredictionResultsByScenarioStmt:   q.getPredictionResultsByScenarioStmt,
		getRouteStmt:                         q.getRouteStmt,
		listCarbonCreditsStmt:                q.listCarbonCreditsStmt,
		listDataCentersStmt:                  q.listDataCentersStmt,
		listDemandSitesStmt:                  q.listDemandSitesStmt,
		listHeatCentersStmt:                  q.listHeatCentersStmt,
		listHeatSinksStmt:                    q.listHeatSinksStmt,
		listPredictionResultsStmt:            q.listPredictionResultsStmt,
		listRoutesStmt:                       q.listRoutesStmt,
		updateCarbonCreditStmt:               q.updateCarbonCreditStmt,
		updateDataCenterStmt:                 q.updateDataCenterStmt,
		updateDemandSiteStmt:                 q.updateDemandSiteStmt,
		updateHeatCenterStmt:                 q.updateHeatCenterStmt,
		updateHeatSinkStmt:                   q.updateHeatSinkStmt,
		updateRouteStmt:                      q.updateRouteStmt,
	}
}
