// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: demand_sites.sql

package database

import (
	"context"
	"database/sql"
)

const countDemandSites = `-- name: CountDemandSites :one
SELECT COUNT(*) FROM demand_sites
`

func (q *Queries) CountDemandSites(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countDemandSitesStmt, countDemandSites)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDemandSite = `-- name: CreateDemandSite :one
INSERT INTO demand_sites (
    name,
    location_lat,
    location_lng,
    address,
    site_type,
    peak_demand_mw,
    current_demand_mw,
    annual_consumption_mwh,
    is_connected,
    connection_date,
    priority_level,
    floor_area_sqm,
    building_age_years,
    insulation_rating,
    description
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, location_lat, location_lng, address, site_type, peak_demand_mw, current_demand_mw, annual_consumption_mwh, is_connected, connection_date, priority_level, floor_area_sqm, building_age_years, insulation_rating, description, created_at, updated_at
`

type CreateDemandSiteParams struct {
	Name                 string          `json:"name"`
	LocationLat          float64         `json:"location_lat"`
	LocationLng          float64         `json:"location_lng"`
	Address              sql.NullString  `json:"address"`
	SiteType             sql.NullString  `json:"site_type"`
	PeakDemandMw         float64         `json:"peak_demand_mw"`
	CurrentDemandMw      sql.NullFloat64 `json:"current_demand_mw"`
	AnnualConsumptionMwh sql.NullFloat64 `json:"annual_consumption_mwh"`
	IsConnected          sql.NullInt64   `json:"is_connected"`
	ConnectionDate       sql.NullString  `json:"connection_date"`
	PriorityLevel        sql.NullInt64   `json:"priority_level"`
	FloorAreaSqm         sql.NullFloat64 `json:"floor_area_sqm"`
	BuildingAgeYears     sql.NullInt64   `json:"building_age_years"`
	InsulationRating     sql.NullString  `json:"insulation_rating"`
	Description          sql.NullString  `json:"description"`
}

func (q *Queries) CreateDemandSite(ctx context.Context, arg CreateDemandSiteParams) (DemandSite, error) {
	row := q.queryRow(ctx, q.createDemandSiteStmt, createDemandSite,
		arg.Name,
		arg.LocationLat,
		arg.LocationLng,
		arg.Address,
		arg.SiteType,
		arg.PeakDemandMw,
		arg.CurrentDemandMw,
		arg.AnnualConsumptionMwh,
		arg.IsConnected,
		arg.ConnectionDate,
		arg.PriorityLevel,
		arg.FloorAreaSqm,
		arg.BuildingAgeYears,
		arg.InsulationRating,
		arg.Description,
	)
	var i DemandSite
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LocationLat,
		&i.LocationLng,
		&i.Address,
		&i.SiteType,
		&i.PeakDemandMw,
		&i.CurrentDemandMw,
		&i.AnnualConsumptionMwh,
		&i.IsConnected,
		&i.ConnectionDate,
		&i.PriorityLevel,
		&i.FloorAreaSqm,
		&i.BuildingAgeYears,
		&i.InsulationRating,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDemandSite = `-- name: DeleteDemandSite :exec
DELETE FROM demand_sites
WHERE id = ?
`

func (q *Queries) DeleteDemandSite(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteDemandSiteStmt, deleteDemandSite, id)
	return err
}

const getDemandSite = `-- name: GetDemandSite :one
SELECT id, name, location_lat, location_lng, address, site_type, peak_demand_mw, current_demand_mw, annual_consumption_mwh, is_connected, connection_date, priority_level, floor_area_sqm, building_age_years, insulation_rating, description, created_at, updated_at FROM demand_sites
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetDemandSite(ctx context.Context, id int64) (DemandSite, error) {
	row := q.queryRow(ctx, q.getDemandSiteStmt, getDemandSite, id)
	var i DemandSite
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LocationLat,
		&i.LocationLng,
		&i.Address,
		&i.SiteType,
		&i.PeakDemandMw,
		&i.CurrentDemandMw,
		&i.AnnualConsumptionMwh,
		&i.IsConnected,
		&i.ConnectionDate,
		&i.PriorityLevel,
		&i.FloorAreaSqm,
		&i.BuildingAgeYears,
		&i.InsulationRating,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDemandSites = `-- name: ListDemandSites :many
SELECT id, name, location_lat, location_lng, address, site_type, peak_demand_mw, current_demand_mw, annual_consumption_mwh, is_connected, connection_date, priority_level, floor_area_sqm, building_age_years, insulation_rating, description, created_at, updated_at FROM demand_sites
ORDER BY name
LIMIT ? OFFSET ?
`

type ListDemandSitesParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListDemandSites(ctx context.Context, arg ListDemandSitesParams) ([]DemandSite, error) {
	rows, err := q.query(ctx, q.listDemandSitesStmt, listDemandSites, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DemandSite{}
	for rows.Next() {
		var i DemandSite
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LocationLat,
			&i.LocationLng,
			&i.Address,
			&i.SiteType,
			&i.PeakDemandMw,
			&i.CurrentDemandMw,
			&i.AnnualConsumptionMwh,
			&i.IsConnected,
			&i.ConnectionDate,
			&i.PriorityLevel,
			&i.FloorAreaSqm,
			&i.BuildingAgeYears,
			&i.InsulationRating,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDemandSite = `-- name: UpdateDemandSite :one
UPDATE demand_sites
SET
    name = COALESCE(?, name),
    location_lat = COALESCE(?, location_lat),
    location_lng = COALESCE(?, location_lng),
    address = COALESCE(?, address),
    site_type = COALESCE(?, site_type),
    peak_demand_mw = COALESCE(?, peak_demand_mw),
    current_demand_mw = COALESCE(?, current_demand_mw),
    annual_consumption_mwh = COALESCE(?, annual_consumption_mwh),
    is_connected = COALESCE(?, is_connected),
    connection_date = COALESCE(?, connection_date),
    priority_level = COALESCE(?, priority_level),
    floor_area_sqm = COALESCE(?, floor_area_sqm),
    building_age_years = COALESCE(?, building_age_years),
    insulation_rating = COALESCE(?, insulation_rating),
    description = COALESCE(?, description),
    updated_at = datetime('now')
WHERE id = ?
RETURNING id, name, location_lat, location_lng, address, site_type, peak_demand_mw, current_demand_mw, annual_consumption_mwh, is_connected, connection_date, priority_level, floor_area_sqm, building_age_years, insulation_rating, description, created_at, updated_at
`

type UpdateDemandSiteParams struct {
	Name                 string          `json:"name"`
	LocationLat          float64         `json:"location_lat"`
	LocationLng          float64         `json:"location_lng"`
	Address              sql.NullString  `json:"address"`
	SiteType             sql.NullString  `json:"site_type"`
	PeakDemandMw         float64         `json:"peak_demand_mw"`
	CurrentDemandMw      sql.NullFloat64 `json:"current_demand_mw"`
	AnnualConsumptionMwh sql.NullFloat64 `json:"annual_consumption_mwh"`
	IsConnected          sql.NullInt64   `json:"is_connected"`
	ConnectionDate       sql.NullString  `json:"connection_date"`
	PriorityLevel        sql.NullInt64   `json:"priority_level"`
	FloorAreaSqm         sql.NullFloat64 `json:"floor_area_sqm"`
	BuildingAgeYears     sql.NullInt64   `json:"building_age_years"`
	InsulationRating     sql.NullString  `json:"insulation_rating"`
	Description          sql.NullString  `json:"description"`
	ID                   int64           `json:"id"`
}

func (q *Queries) UpdateDemandSite(ctx context.Context, arg UpdateDemandSiteParams) (DemandSite, error) {
	row := q.queryRow(ctx, q.updateDemandSiteStmt, updateDemandSite,
		arg.Name,
		arg.LocationLat,
		arg.LocationLng,
		arg.Address,
		arg.SiteType,
		arg.PeakDemandMw,
		arg.CurrentDemandMw,
		arg.AnnualConsumptionMwh,
		arg.IsConnected,
		arg.ConnectionDate,
		arg.PriorityLevel,
		arg.FloorAreaSqm,
		arg.BuildingAgeYears,
		arg.InsulationRating,
		arg.Description,
		arg.ID,
	)
	var i DemandSite
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LocationLat,
		&i.LocationLng,
		&i.Address,
		&i.SiteType,
		&i.PeakDemandMw,
		&i.CurrentDemandMw,
		&i.AnnualConsumptionMwh,
		&i.IsConnected,
		&i.ConnectionDate,
		&i.PriorityLevel,
		&i.FloorAreaSqm,
		&i.BuildingAgeYears,
		&i.InsulationRating,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
