// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feasibility_assessments.sql

package database

import (
	"context"
	"database/sql"
)

const countAssessments = `-- name: CountAssessments :one
SELECT COUNT(*) FROM feasibility_assessments
`

func (q *Queries) CountAssessments(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countAssessmentsStmt, countAssessments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAssessmentsByStatus = `-- name: CountAssessmentsByStatus :one
SELECT COUNT(*) FROM feasibility_assessments WHERE status = ?
`

func (q *Queries) CountAssessmentsByStatus(ctx context.Context, status string) (int64, error) {
	row := q.queryRow(ctx, q.countAssessmentsByStatusStmt, countAssessmentsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAssessment = `-- name: CreateAssessment :one
INSERT INTO feasibility_assessments (
    project_name,
    dc_location_lat,
    dc_location_lng,
    thermal_load_min_kw,
    thermal_load_max_kw,
    availability_profile,
    uptime_constraint,
    existing_cooling,
    investment_willingness,
    distance_to_offtaker_km,
    heat_demand_profile,
    supply_temp_required_c,
    existing_dh_infra,
    jurisdiction,
    applicable_regulation,
    time_horizon_years,
    status
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
) RETURNING id, version, project_name, dc_location_lat, dc_location_lng, thermal_load_min_kw, thermal_load_max_kw, availability_profile, uptime_constraint, existing_cooling, investment_willingness, distance_to_offtaker_km, heat_demand_profile, supply_temp_required_c, existing_dh_infra, jurisdiction, applicable_regulation, time_horizon_years, status, scenario_results, compliance_result, conclusion, created_at, updated_at, submitted_at, completed_at, stakeholders_json, risk_allocation_json, audit_trail_json, record_version, prepared_by, confidence_level
`

type CreateAssessmentParams struct {
	ProjectName           string  `json:"project_name"`
	DcLocationLat         float64 `json:"dc_location_lat"`
	DcLocationLng         float64 `json:"dc_location_lng"`
	ThermalLoadMinKw      float64 `json:"thermal_load_min_kw"`
	ThermalLoadMaxKw      float64 `json:"thermal_load_max_kw"`
	AvailabilityProfile   string  `json:"availability_profile"`
	UptimeConstraint      string  `json:"uptime_constraint"`
	ExistingCooling       int64   `json:"existing_cooling"`
	InvestmentWillingness string  `json:"investment_willingness"`
	DistanceToOfftakerKm  float64 `json:"distance_to_offtaker_km"`
	HeatDemandProfile     string  `json:"heat_demand_profile"`
	SupplyTempRequiredC   float64 `json:"supply_temp_required_c"`
	ExistingDhInfra       int64   `json:"existing_dh_infra"`
	Jurisdiction          string  `json:"jurisdiction"`
	ApplicableRegulation  string  `json:"applicable_regulation"`
	TimeHorizonYears      int64   `json:"time_horizon_years"`
	Status                string  `json:"status"`
}

func (q *Queries) CreateAssessment(ctx context.Context, arg CreateAssessmentParams) (FeasibilityAssessment, error) {
	row := q.queryRow(ctx, q.createAssessmentStmt, createAssessment,
		arg.ProjectName,
		arg.DcLocationLat,
		arg.DcLocationLng,
		arg.ThermalLoadMinKw,
		arg.ThermalLoadMaxKw,
		arg.AvailabilityProfile,
		arg.UptimeConstraint,
		arg.ExistingCooling,
		arg.InvestmentWillingness,
		arg.DistanceToOfftakerKm,
		arg.HeatDemandProfile,
		arg.SupplyTempRequiredC,
		arg.ExistingDhInfra,
		arg.Jurisdiction,
		arg.ApplicableRegulation,
		arg.TimeHorizonYears,
		arg.Status,
	)
	var i FeasibilityAssessment
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.ProjectName,
		&i.DcLocationLat,
		&i.DcLocationLng,
		&i.ThermalLoadMinKw,
		&i.ThermalLoadMaxKw,
		&i.AvailabilityProfile,
		&i.UptimeConstraint,
		&i.ExistingCooling,
		&i.InvestmentWillingness,
		&i.DistanceToOfftakerKm,
		&i.HeatDemandProfile,
		&i.SupplyTempRequiredC,
		&i.ExistingDhInfra,
		&i.Jurisdiction,
		&i.ApplicableRegulation,
		&i.TimeHorizonYears,
		&i.Status,
		&i.ScenarioResults,
		&i.ComplianceResult,
		&i.Conclusion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.CompletedAt,
		&i.StakeholdersJson,
		&i.RiskAllocationJson,
		&i.AuditTrailJson,
		&i.RecordVersion,
		&i.PreparedBy,
		&i.ConfidenceLevel,
	)
	return i, err
}

const deleteAssessment = `-- name: DeleteAssessment :exec
DELETE FROM feasibility_assessments WHERE id = ?
`

func (q *Queries) DeleteAssessment(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteAssessmentStmt, deleteAssessment, id)
	return err
}

const getAssessment = `-- name: GetAssessment :one
SELECT id, version, project_name, dc_location_lat, dc_location_lng, thermal_load_min_kw, thermal_load_max_kw, availability_profile, uptime_constraint, existing_cooling, investment_willingness, distance_to_offtaker_km, heat_demand_profile, supply_temp_required_c, existing_dh_infra, jurisdiction, applicable_regulation, time_horizon_years, status, scenario_results, compliance_result, conclusion, created_at, updated_at, submitted_at, completed_at, stakeholders_json, risk_allocation_json, audit_trail_json, record_version, prepared_by, confidence_level FROM feasibility_assessments WHERE id = ?
`

func (q *Queries) GetAssessment(ctx context.Context, id int64) (FeasibilityAssessment, error) {
	row := q.queryRow(ctx, q.getAssessmentStmt, getAssessment, id)
	var i FeasibilityAssessment
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.ProjectName,
		&i.DcLocationLat,
		&i.DcLocationLng,
		&i.ThermalLoadMinKw,
		&i.ThermalLoadMaxKw,
		&i.AvailabilityProfile,
		&i.UptimeConstraint,
		&i.ExistingCooling,
		&i.InvestmentWillingness,
		&i.DistanceToOfftakerKm,
		&i.HeatDemandProfile,
		&i.SupplyTempRequiredC,
		&i.ExistingDhInfra,
		&i.Jurisdiction,
		&i.ApplicableRegulation,
		&i.TimeHorizonYears,
		&i.Status,
		&i.ScenarioResults,
		&i.ComplianceResult,
		&i.Conclusion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.CompletedAt,
		&i.StakeholdersJson,
		&i.RiskAllocationJson,
		&i.AuditTrailJson,
		&i.RecordVersion,
		&i.PreparedBy,
		&i.ConfidenceLevel,
	)
	return i, err
}

const getAssessmentsByJurisdiction = `-- name: GetAssessmentsByJurisdiction :many
SELECT id, version, project_name, dc_location_lat, dc_location_lng, thermal_load_min_kw, thermal_load_max_kw, availability_profile, uptime_constraint, existing_cooling, investment_willingness, distance_to_offtaker_km, heat_demand_profile, supply_temp_required_c, existing_dh_infra, jurisdiction, applicable_regulation, time_horizon_years, status, scenario_results, compliance_result, conclusion, created_at, updated_at, submitted_at, completed_at, stakeholders_json, risk_allocation_json, audit_trail_json, record_version, prepared_by, confidence_level FROM feasibility_assessments 
WHERE jurisdiction = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type GetAssessmentsByJurisdictionParams struct {
	Jurisdiction string `json:"jurisdiction"`
	Limit        int64  `json:"limit"`
	Offset       int64  `json:"offset"`
}

func (q *Queries) GetAssessmentsByJurisdiction(ctx context.Context, arg GetAssessmentsByJurisdictionParams) ([]FeasibilityAssessment, error) {
	rows, err := q.query(ctx, q.getAssessmentsByJurisdictionStmt, getAssessmentsByJurisdiction, arg.Jurisdiction, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FeasibilityAssessment{}
	for rows.Next() {
		var i FeasibilityAssessment
		if err := rows.Scan(
			&i.ID,
			&i.Version,
			&i.ProjectName,
			&i.DcLocationLat,
			&i.DcLocationLng,
			&i.ThermalLoadMinKw,
			&i.ThermalLoadMaxKw,
			&i.AvailabilityProfile,
			&i.UptimeConstraint,
			&i.ExistingCooling,
			&i.InvestmentWillingness,
			&i.DistanceToOfftakerKm,
			&i.HeatDemandProfile,
			&i.SupplyTempRequiredC,
			&i.ExistingDhInfra,
			&i.Jurisdiction,
			&i.ApplicableRegulation,
			&i.TimeHorizonYears,
			&i.Status,
			&i.ScenarioResults,
			&i.ComplianceResult,
			&i.Conclusion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubmittedAt,
			&i.CompletedAt,
			&i.StakeholdersJson,
			&i.RiskAllocationJson,
			&i.AuditTrailJson,
			&i.RecordVersion,
			&i.PreparedBy,
			&i.ConfidenceLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementAssessmentVersion = `-- name: IncrementAssessmentVersion :one
UPDATE feasibility_assessments SET
    version = version + 1,
    scenario_results = NULL,
    compliance_result = NULL,
    conclusion = NULL,
    status = 'draft',
    updated_at = datetime('now'),
    completed_at = NULL
WHERE id = ?
RETURNING id, version, project_name, dc_location_lat, dc_location_lng, thermal_load_min_kw, thermal_load_max_kw, availability_profile, uptime_constraint, existing_cooling, investment_willingness, distance_to_offtaker_km, heat_demand_profile, supply_temp_required_c, existing_dh_infra, jurisdiction, applicable_regulation, time_horizon_years, status, scenario_results, compliance_result, conclusion, created_at, updated_at, submitted_at, completed_at, stakeholders_json, risk_allocation_json, audit_trail_json, record_version, prepared_by, confidence_level
`

func (q *Queries) IncrementAssessmentVersion(ctx context.Context, id int64) (FeasibilityAssessment, error) {
	row := q.queryRow(ctx, q.incrementAssessmentVersionStmt, incrementAssessmentVersion, id)
	var i FeasibilityAssessment
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.ProjectName,
		&i.DcLocationLat,
		&i.DcLocationLng,
		&i.ThermalLoadMinKw,
		&i.ThermalLoadMaxKw,
		&i.AvailabilityProfile,
		&i.UptimeConstraint,
		&i.ExistingCooling,
		&i.InvestmentWillingness,
		&i.DistanceToOfftakerKm,
		&i.HeatDemandProfile,
		&i.SupplyTempRequiredC,
		&i.ExistingDhInfra,
		&i.Jurisdiction,
		&i.ApplicableRegulation,
		&i.TimeHorizonYears,
		&i.Status,
		&i.ScenarioResults,
		&i.ComplianceResult,
		&i.Conclusion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.CompletedAt,
		&i.StakeholdersJson,
		&i.RiskAllocationJson,
		&i.AuditTrailJson,
		&i.RecordVersion,
		&i.PreparedBy,
		&i.ConfidenceLevel,
	)
	return i, err
}

const listAssessments = `-- name: ListAssessments :many
SELECT id, version, project_name, dc_location_lat, dc_location_lng, thermal_load_min_kw, thermal_load_max_kw, availability_profile, uptime_constraint, existing_cooling, investment_willingness, distance_to_offtaker_km, heat_demand_profile, supply_temp_required_c, existing_dh_infra, jurisdiction, applicable_regulation, time_horizon_years, status, scenario_results, compliance_result, conclusion, created_at, updated_at, submitted_at, completed_at, stakeholders_json, risk_allocation_json, audit_trail_json, record_version, prepared_by, confidence_level FROM feasibility_assessments 
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListAssessmentsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListAssessments(ctx context.Context, arg ListAssessmentsParams) ([]FeasibilityAssessment, error) {
	rows, err := q.query(ctx, q.listAssessmentsStmt, listAssessments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FeasibilityAssessment{}
	for rows.Next() {
		var i FeasibilityAssessment
		if err := rows.Scan(
			&i.ID,
			&i.Version,
			&i.ProjectName,
			&i.DcLocationLat,
			&i.DcLocationLng,
			&i.ThermalLoadMinKw,
			&i.ThermalLoadMaxKw,
			&i.AvailabilityProfile,
			&i.UptimeConstraint,
			&i.ExistingCooling,
			&i.InvestmentWillingness,
			&i.DistanceToOfftakerKm,
			&i.HeatDemandProfile,
			&i.SupplyTempRequiredC,
			&i.ExistingDhInfra,
			&i.Jurisdiction,
			&i.ApplicableRegulation,
			&i.TimeHorizonYears,
			&i.Status,
			&i.ScenarioResults,
			&i.ComplianceResult,
			&i.Conclusion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubmittedAt,
			&i.CompletedAt,
			&i.StakeholdersJson,
			&i.RiskAllocationJson,
			&i.AuditTrailJson,
			&i.RecordVersion,
			&i.PreparedBy,
			&i.ConfidenceLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssessmentsByStatus = `-- name: ListAssessmentsByStatus :many
SELECT id, version, project_name, dc_location_lat, dc_location_lng, thermal_load_min_kw, thermal_load_max_kw, availability_profile, uptime_constraint, existing_cooling, investment_willingness, distance_to_offtaker_km, heat_demand_profile, supply_temp_required_c, existing_dh_infra, jurisdiction, applicable_regulation, time_horizon_years, status, scenario_results, compliance_result, conclusion, created_at, updated_at, submitted_at, completed_at, stakeholders_json, risk_allocation_json, audit_trail_json, record_version, prepared_by, confidence_level FROM feasibility_assessments 
WHERE status = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListAssessmentsByStatusParams struct {
	Status string `json:"status"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListAssessmentsByStatus(ctx context.Context, arg ListAssessmentsByStatusParams) ([]FeasibilityAssessment, error) {
	rows, err := q.query(ctx, q.listAssessmentsByStatusStmt, listAssessmentsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FeasibilityAssessment{}
	for rows.Next() {
		var i FeasibilityAssessment
		if err := rows.Scan(
			&i.ID,
			&i.Version,
			&i.ProjectName,
			&i.DcLocationLat,
			&i.DcLocationLng,
			&i.ThermalLoadMinKw,
			&i.ThermalLoadMaxKw,
			&i.AvailabilityProfile,
			&i.UptimeConstraint,
			&i.ExistingCooling,
			&i.InvestmentWillingness,
			&i.DistanceToOfftakerKm,
			&i.HeatDemandProfile,
			&i.SupplyTempRequiredC,
			&i.ExistingDhInfra,
			&i.Jurisdiction,
			&i.ApplicableRegulation,
			&i.TimeHorizonYears,
			&i.Status,
			&i.ScenarioResults,
			&i.ComplianceResult,
			&i.Conclusion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubmittedAt,
			&i.CompletedAt,
			&i.StakeholdersJson,
			&i.RiskAllocationJson,
			&i.AuditTrailJson,
			&i.RecordVersion,
			&i.PreparedBy,
			&i.ConfidenceLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAssessmentDecisionRecord = `-- name: UpdateAssessmentDecisionRecord :one
UPDATE feasibility_assessments SET
    stakeholders_json = ?,
    risk_allocation_json = ?,
    audit_trail_json = ?,
    record_version = ?,
    prepared_by = ?,
    confidence_level = ?,
    updated_at = datetime('now')
WHERE id = ?
RETURNING id, version, project_name, dc_location_lat, dc_location_lng, thermal_load_min_kw, thermal_load_max_kw, availability_profile, uptime_constraint, existing_cooling, investment_willingness, distance_to_offtaker_km, heat_demand_profile, supply_temp_required_c, existing_dh_infra, jurisdiction, applicable_regulation, time_horizon_years, status, scenario_results, compliance_result, conclusion, created_at, updated_at, submitted_at, completed_at, stakeholders_json, risk_allocation_json, audit_trail_json, record_version, prepared_by, confidence_level
`

type UpdateAssessmentDecisionRecordParams struct {
	StakeholdersJson   sql.NullString `json:"stakeholders_json"`
	RiskAllocationJson sql.NullString `json:"risk_allocation_json"`
	AuditTrailJson     sql.NullString `json:"audit_trail_json"`
	RecordVersion      sql.NullString `json:"record_version"`
	PreparedBy         sql.NullString `json:"prepared_by"`
	ConfidenceLevel    sql.NullString `json:"confidence_level"`
	ID                 int64          `json:"id"`
}

func (q *Queries) UpdateAssessmentDecisionRecord(ctx context.Context, arg UpdateAssessmentDecisionRecordParams) (FeasibilityAssessment, error) {
	row := q.queryRow(ctx, q.updateAssessmentDecisionRecordStmt, updateAssessmentDecisionRecord,
		arg.StakeholdersJson,
		arg.RiskAllocationJson,
		arg.AuditTrailJson,
		arg.RecordVersion,
		arg.PreparedBy,
		arg.ConfidenceLevel,
		arg.ID,
	)
	var i FeasibilityAssessment
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.ProjectName,
		&i.DcLocationLat,
		&i.DcLocationLng,
		&i.ThermalLoadMinKw,
		&i.ThermalLoadMaxKw,
		&i.AvailabilityProfile,
		&i.UptimeConstraint,
		&i.ExistingCooling,
		&i.InvestmentWillingness,
		&i.DistanceToOfftakerKm,
		&i.HeatDemandProfile,
		&i.SupplyTempRequiredC,
		&i.ExistingDhInfra,
		&i.Jurisdiction,
		&i.ApplicableRegulation,
		&i.TimeHorizonYears,
		&i.Status,
		&i.ScenarioResults,
		&i.ComplianceResult,
		&i.Conclusion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.CompletedAt,
		&i.StakeholdersJson,
		&i.RiskAllocationJson,
		&i.AuditTrailJson,
		&i.RecordVersion,
		&i.PreparedBy,
		&i.ConfidenceLevel,
	)
	return i, err
}

const updateAssessmentFullResults = `-- name: UpdateAssessmentFullResults :one
UPDATE feasibility_assessments SET
    scenario_results = ?,
    compliance_result = ?,
    risk_allocation_json = ?,
    conclusion = ?,
    confidence_level = ?,
    status = ?,
    updated_at = datetime('now'),
    completed_at = CASE WHEN ? = 'completed' THEN datetime('now') ELSE completed_at END
WHERE id = ?
RETURNING id, version, project_name, dc_location_lat, dc_location_lng, thermal_load_min_kw, thermal_load_max_kw, availability_profile, uptime_constraint, existing_cooling, investment_willingness, distance_to_offtaker_km, heat_demand_profile, supply_temp_required_c, existing_dh_infra, jurisdiction, applicable_regulation, time_horizon_years, status, scenario_results, compliance_result, conclusion, created_at, updated_at, submitted_at, completed_at, stakeholders_json, risk_allocation_json, audit_trail_json, record_version, prepared_by, confidence_level
`

type UpdateAssessmentFullResultsParams struct {
	ScenarioResults    sql.NullString `json:"scenario_results"`
	ComplianceResult   sql.NullString `json:"compliance_result"`
	RiskAllocationJson sql.NullString `json:"risk_allocation_json"`
	Conclusion         sql.NullString `json:"conclusion"`
	ConfidenceLevel    sql.NullString `json:"confidence_level"`
	Status             string         `json:"status"`
	Column7            interface{}    `json:"column_7"`
	ID                 int64          `json:"id"`
}

func (q *Queries) UpdateAssessmentFullResults(ctx context.Context, arg UpdateAssessmentFullResultsParams) (FeasibilityAssessment, error) {
	row := q.queryRow(ctx, q.updateAssessmentFullResultsStmt, updateAssessmentFullResults,
		arg.ScenarioResults,
		arg.ComplianceResult,
		arg.RiskAllocationJson,
		arg.Conclusion,
		arg.ConfidenceLevel,
		arg.Status,
		arg.Column7,
		arg.ID,
	)
	var i FeasibilityAssessment
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.ProjectName,
		&i.DcLocationLat,
		&i.DcLocationLng,
		&i.ThermalLoadMinKw,
		&i.ThermalLoadMaxKw,
		&i.AvailabilityProfile,
		&i.UptimeConstraint,
		&i.ExistingCooling,
		&i.InvestmentWillingness,
		&i.DistanceToOfftakerKm,
		&i.HeatDemandProfile,
		&i.SupplyTempRequiredC,
		&i.ExistingDhInfra,
		&i.Jurisdiction,
		&i.ApplicableRegulation,
		&i.TimeHorizonYears,
		&i.Status,
		&i.ScenarioResults,
		&i.ComplianceResult,
		&i.Conclusion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.CompletedAt,
		&i.StakeholdersJson,
		&i.RiskAllocationJson,
		&i.AuditTrailJson,
		&i.RecordVersion,
		&i.PreparedBy,
		&i.ConfidenceLevel,
	)
	return i, err
}

const updateAssessmentInputs = `-- name: UpdateAssessmentInputs :one
UPDATE feasibility_assessments SET
    project_name = ?,
    dc_location_lat = ?,
    dc_location_lng = ?,
    thermal_load_min_kw = ?,
    thermal_load_max_kw = ?,
    availability_profile = ?,
    uptime_constraint = ?,
    existing_cooling = ?,
    investment_willingness = ?,
    distance_to_offtaker_km = ?,
    heat_demand_profile = ?,
    supply_temp_required_c = ?,
    existing_dh_infra = ?,
    jurisdiction = ?,
    applicable_regulation = ?,
    time_horizon_years = ?,
    updated_at = datetime('now')
WHERE id = ?
RETURNING id, version, project_name, dc_location_lat, dc_location_lng, thermal_load_min_kw, thermal_load_max_kw, availability_profile, uptime_constraint, existing_cooling, investment_willingness, distance_to_offtaker_km, heat_demand_profile, supply_temp_required_c, existing_dh_infra, jurisdiction, applicable_regulation, time_horizon_years, status, scenario_results, compliance_result, conclusion, created_at, updated_at, submitted_at, completed_at, stakeholders_json, risk_allocation_json, audit_trail_json, record_version, prepared_by, confidence_level
`

type UpdateAssessmentInputsParams struct {
	ProjectName           string  `json:"project_name"`
	DcLocationLat         float64 `json:"dc_location_lat"`
	DcLocationLng         float64 `json:"dc_location_lng"`
	ThermalLoadMinKw      float64 `json:"thermal_load_min_kw"`
	ThermalLoadMaxKw      float64 `json:"thermal_load_max_kw"`
	AvailabilityProfile   string  `json:"availability_profile"`
	UptimeConstraint      string  `json:"uptime_constraint"`
	ExistingCooling       int64   `json:"existing_cooling"`
	InvestmentWillingness string  `json:"investment_willingness"`
	DistanceToOfftakerKm  float64 `json:"distance_to_offtaker_km"`
	HeatDemandProfile     string  `json:"heat_demand_profile"`
	SupplyTempRequiredC   float64 `json:"supply_temp_required_c"`
	ExistingDhInfra       int64   `json:"existing_dh_infra"`
	Jurisdiction          string  `json:"jurisdiction"`
	ApplicableRegulation  string  `json:"applicable_regulation"`
	TimeHorizonYears      int64   `json:"time_horizon_years"`
	ID                    int64   `json:"id"`
}

func (q *Queries) UpdateAssessmentInputs(ctx context.Context, arg UpdateAssessmentInputsParams) (FeasibilityAssessment, error) {
	row := q.queryRow(ctx, q.updateAssessmentInputsStmt, updateAssessmentInputs,
		arg.ProjectName,
		arg.DcLocationLat,
		arg.DcLocationLng,
		arg.ThermalLoadMinKw,
		arg.ThermalLoadMaxKw,
		arg.AvailabilityProfile,
		arg.UptimeConstraint,
		arg.ExistingCooling,
		arg.InvestmentWillingness,
		arg.DistanceToOfftakerKm,
		arg.HeatDemandProfile,
		arg.SupplyTempRequiredC,
		arg.ExistingDhInfra,
		arg.Jurisdiction,
		arg.ApplicableRegulation,
		arg.TimeHorizonYears,
		arg.ID,
	)
	var i FeasibilityAssessment
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.ProjectName,
		&i.DcLocationLat,
		&i.DcLocationLng,
		&i.ThermalLoadMinKw,
		&i.ThermalLoadMaxKw,
		&i.AvailabilityProfile,
		&i.UptimeConstraint,
		&i.ExistingCooling,
		&i.InvestmentWillingness,
		&i.DistanceToOfftakerKm,
		&i.HeatDemandProfile,
		&i.SupplyTempRequiredC,
		&i.ExistingDhInfra,
		&i.Jurisdiction,
		&i.ApplicableRegulation,
		&i.TimeHorizonYears,
		&i.Status,
		&i.ScenarioResults,
		&i.ComplianceResult,
		&i.Conclusion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.CompletedAt,
		&i.StakeholdersJson,
		&i.RiskAllocationJson,
		&i.AuditTrailJson,
		&i.RecordVersion,
		&i.PreparedBy,
		&i.ConfidenceLevel,
	)
	return i, err
}

const updateAssessmentResults = `-- name: UpdateAssessmentResults :one
UPDATE feasibility_assessments SET
    scenario_results = ?,
    compliance_result = ?,
    conclusion = ?,
    status = ?,
    updated_at = datetime('now'),
    completed_at = CASE WHEN ? = 'completed' THEN datetime('now') ELSE completed_at END
WHERE id = ?
RETURNING id, version, project_name, dc_location_lat, dc_location_lng, thermal_load_min_kw, thermal_load_max_kw, availability_profile, uptime_constraint, existing_cooling, investment_willingness, distance_to_offtaker_km, heat_demand_profile, supply_temp_required_c, existing_dh_infra, jurisdiction, applicable_regulation, time_horizon_years, status, scenario_results, compliance_result, conclusion, created_at, updated_at, submitted_at, completed_at, stakeholders_json, risk_allocation_json, audit_trail_json, record_version, prepared_by, confidence_level
`

type UpdateAssessmentResultsParams struct {
	ScenarioResults  sql.NullString `json:"scenario_results"`
	ComplianceResult sql.NullString `json:"compliance_result"`
	Conclusion       sql.NullString `json:"conclusion"`
	Status           string         `json:"status"`
	Column5          interface{}    `json:"column_5"`
	ID               int64          `json:"id"`
}

func (q *Queries) UpdateAssessmentResults(ctx context.Context, arg UpdateAssessmentResultsParams) (FeasibilityAssessment, error) {
	row := q.queryRow(ctx, q.updateAssessmentResultsStmt, updateAssessmentResults,
		arg.ScenarioResults,
		arg.ComplianceResult,
		arg.Conclusion,
		arg.Status,
		arg.Column5,
		arg.ID,
	)
	var i FeasibilityAssessment
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.ProjectName,
		&i.DcLocationLat,
		&i.DcLocationLng,
		&i.ThermalLoadMinKw,
		&i.ThermalLoadMaxKw,
		&i.AvailabilityProfile,
		&i.UptimeConstraint,
		&i.ExistingCooling,
		&i.InvestmentWillingness,
		&i.DistanceToOfftakerKm,
		&i.HeatDemandProfile,
		&i.SupplyTempRequiredC,
		&i.ExistingDhInfra,
		&i.Jurisdiction,
		&i.ApplicableRegulation,
		&i.TimeHorizonYears,
		&i.Status,
		&i.ScenarioResults,
		&i.ComplianceResult,
		&i.Conclusion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.CompletedAt,
		&i.StakeholdersJson,
		&i.RiskAllocationJson,
		&i.AuditTrailJson,
		&i.RecordVersion,
		&i.PreparedBy,
		&i.ConfidenceLevel,
	)
	return i, err
}
