// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: heat_sinks.sql

package database

import (
	"context"
	"database/sql"
)

const countHeatSinks = `-- name: CountHeatSinks :one
SELECT COUNT(*) FROM heat_sinks
`

func (q *Queries) CountHeatSinks(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countHeatSinksStmt, countHeatSinks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createHeatSink = `-- name: CreateHeatSink :one
INSERT INTO heat_sinks (
    name,
    location_lat,
    location_lng,
    address,
    sink_type,
    capacity_mw,
    current_demand_mw,
    temperature_requirement_c,
    seasonal_factor,
    connection_cost_per_km,
    heat_price_per_mwh,
    operating_hours_year
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, location_lat, location_lng, address, sink_type, capacity_mw, current_demand_mw, temperature_requirement_c, seasonal_factor, connection_cost_per_km, heat_price_per_mwh, operating_hours_year, created_at
`

type CreateHeatSinkParams struct {
	Name                    string          `json:"name"`
	LocationLat             float64         `json:"location_lat"`
	LocationLng             float64         `json:"location_lng"`
	Address                 sql.NullString  `json:"address"`
	SinkType                sql.NullString  `json:"sink_type"`
	CapacityMw              float64         `json:"capacity_mw"`
	CurrentDemandMw         sql.NullFloat64 `json:"current_demand_mw"`
	TemperatureRequirementC sql.NullFloat64 `json:"temperature_requirement_c"`
	SeasonalFactor          sql.NullFloat64 `json:"seasonal_factor"`
	ConnectionCostPerKm     sql.NullFloat64 `json:"connection_cost_per_km"`
	HeatPricePerMwh         sql.NullFloat64 `json:"heat_price_per_mwh"`
	OperatingHoursYear      sql.NullInt64   `json:"operating_hours_year"`
}

func (q *Queries) CreateHeatSink(ctx context.Context, arg CreateHeatSinkParams) (HeatSink, error) {
	row := q.queryRow(ctx, q.createHeatSinkStmt, createHeatSink,
		arg.Name,
		arg.LocationLat,
		arg.LocationLng,
		arg.Address,
		arg.SinkType,
		arg.CapacityMw,
		arg.CurrentDemandMw,
		arg.TemperatureRequirementC,
		arg.SeasonalFactor,
		arg.ConnectionCostPerKm,
		arg.HeatPricePerMwh,
		arg.OperatingHoursYear,
	)
	var i HeatSink
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LocationLat,
		&i.LocationLng,
		&i.Address,
		&i.SinkType,
		&i.CapacityMw,
		&i.CurrentDemandMw,
		&i.TemperatureRequirementC,
		&i.SeasonalFactor,
		&i.ConnectionCostPerKm,
		&i.HeatPricePerMwh,
		&i.OperatingHoursYear,
		&i.CreatedAt,
	)
	return i, err
}

const deleteHeatSink = `-- name: DeleteHeatSink :exec
DELETE FROM heat_sinks
WHERE id = ?
`

func (q *Queries) DeleteHeatSink(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteHeatSinkStmt, deleteHeatSink, id)
	return err
}

const getHeatSink = `-- name: GetHeatSink :one
SELECT id, name, location_lat, location_lng, address, sink_type, capacity_mw, current_demand_mw, temperature_requirement_c, seasonal_factor, connection_cost_per_km, heat_price_per_mwh, operating_hours_year, created_at FROM heat_sinks
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetHeatSink(ctx context.Context, id int64) (HeatSink, error) {
	row := q.queryRow(ctx, q.getHeatSinkStmt, getHeatSink, id)
	var i HeatSink
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LocationLat,
		&i.LocationLng,
		&i.Address,
		&i.SinkType,
		&i.CapacityMw,
		&i.CurrentDemandMw,
		&i.TemperatureRequirementC,
		&i.SeasonalFactor,
		&i.ConnectionCostPerKm,
		&i.HeatPricePerMwh,
		&i.OperatingHoursYear,
		&i.CreatedAt,
	)
	return i, err
}

const listHeatSinks = `-- name: ListHeatSinks :many
SELECT id, name, location_lat, location_lng, address, sink_type, capacity_mw, current_demand_mw, temperature_requirement_c, seasonal_factor, connection_cost_per_km, heat_price_per_mwh, operating_hours_year, created_at FROM heat_sinks
ORDER BY name
LIMIT ? OFFSET ?
`

type ListHeatSinksParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListHeatSinks(ctx context.Context, arg ListHeatSinksParams) ([]HeatSink, error) {
	rows, err := q.query(ctx, q.listHeatSinksStmt, listHeatSinks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HeatSink{}
	for rows.Next() {
		var i HeatSink
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LocationLat,
			&i.LocationLng,
			&i.Address,
			&i.SinkType,
			&i.CapacityMw,
			&i.CurrentDemandMw,
			&i.TemperatureRequirementC,
			&i.SeasonalFactor,
			&i.ConnectionCostPerKm,
			&i.HeatPricePerMwh,
			&i.OperatingHoursYear,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHeatSink = `-- name: UpdateHeatSink :one
UPDATE heat_sinks
SET
    name = COALESCE(?, name),
    location_lat = COALESCE(?, location_lat),
    location_lng = COALESCE(?, location_lng),
    address = COALESCE(?, address),
    sink_type = COALESCE(?, sink_type),
    capacity_mw = COALESCE(?, capacity_mw),
    current_demand_mw = COALESCE(?, current_demand_mw),
    temperature_requirement_c = COALESCE(?, temperature_requirement_c),
    seasonal_factor = COALESCE(?, seasonal_factor),
    connection_cost_per_km = COALESCE(?, connection_cost_per_km),
    heat_price_per_mwh = COALESCE(?, heat_price_per_mwh),
    operating_hours_year = COALESCE(?, operating_hours_year)
WHERE id = ?
RETURNING id, name, location_lat, location_lng, address, sink_type, capacity_mw, current_demand_mw, temperature_requirement_c, seasonal_factor, connection_cost_per_km, heat_price_per_mwh, operating_hours_year, created_at
`

type UpdateHeatSinkParams struct {
	Name                    string          `json:"name"`
	LocationLat             float64         `json:"location_lat"`
	LocationLng             float64         `json:"location_lng"`
	Address                 sql.NullString  `json:"address"`
	SinkType                sql.NullString  `json:"sink_type"`
	CapacityMw              float64         `json:"capacity_mw"`
	CurrentDemandMw         sql.NullFloat64 `json:"current_demand_mw"`
	TemperatureRequirementC sql.NullFloat64 `json:"temperature_requirement_c"`
	SeasonalFactor          sql.NullFloat64 `json:"seasonal_factor"`
	ConnectionCostPerKm     sql.NullFloat64 `json:"connection_cost_per_km"`
	HeatPricePerMwh         sql.NullFloat64 `json:"heat_price_per_mwh"`
	OperatingHoursYear      sql.NullInt64   `json:"operating_hours_year"`
	ID                      int64           `json:"id"`
}

func (q *Queries) UpdateHeatSink(ctx context.Context, arg UpdateHeatSinkParams) (HeatSink, error) {
	row := q.queryRow(ctx, q.updateHeatSinkStmt, updateHeatSink,
		arg.Name,
		arg.LocationLat,
		arg.LocationLng,
		arg.Address,
		arg.SinkType,
		arg.CapacityMw,
		arg.CurrentDemandMw,
		arg.TemperatureRequirementC,
		arg.SeasonalFactor,
		arg.ConnectionCostPerKm,
		arg.HeatPricePerMwh,
		arg.OperatingHoursYear,
		arg.ID,
	)
	var i HeatSink
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LocationLat,
		&i.LocationLng,
		&i.Address,
		&i.SinkType,
		&i.CapacityMw,
		&i.CurrentDemandMw,
		&i.TemperatureRequirementC,
		&i.SeasonalFactor,
		&i.ConnectionCostPerKm,
		&i.HeatPricePerMwh,
		&i.OperatingHoursYear,
		&i.CreatedAt,
	)
	return i, err
}
