// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: heat_centers.sql

package database

import (
	"context"
	"database/sql"
)

const countHeatCenters = `-- name: CountHeatCenters :one
SELECT COUNT(*) FROM heat_centers
`

func (q *Queries) CountHeatCenters(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countHeatCentersStmt, countHeatCenters)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createHeatCenter = `-- name: CreateHeatCenter :one
INSERT INTO heat_centers (
    name,
    location_lat,
    location_lng,
    address,
    max_capacity_mw,
    current_output_mw,
    efficiency_percent,
    fuel_type,
    is_active,
    commissioning_date,
    last_maintenance,
    description
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, location_lat, location_lng, address, max_capacity_mw, current_output_mw, efficiency_percent, fuel_type, is_active, commissioning_date, last_maintenance, description, created_at, updated_at
`

type CreateHeatCenterParams struct {
	Name              string          `json:"name"`
	LocationLat       float64         `json:"location_lat"`
	LocationLng       float64         `json:"location_lng"`
	Address           sql.NullString  `json:"address"`
	MaxCapacityMw     float64         `json:"max_capacity_mw"`
	CurrentOutputMw   sql.NullFloat64 `json:"current_output_mw"`
	EfficiencyPercent sql.NullFloat64 `json:"efficiency_percent"`
	FuelType          sql.NullString  `json:"fuel_type"`
	IsActive          sql.NullInt64   `json:"is_active"`
	CommissioningDate sql.NullString  `json:"commissioning_date"`
	LastMaintenance   sql.NullString  `json:"last_maintenance"`
	Description       sql.NullString  `json:"description"`
}

func (q *Queries) CreateHeatCenter(ctx context.Context, arg CreateHeatCenterParams) (HeatCenter, error) {
	row := q.queryRow(ctx, q.createHeatCenterStmt, createHeatCenter,
		arg.Name,
		arg.LocationLat,
		arg.LocationLng,
		arg.Address,
		arg.MaxCapacityMw,
		arg.CurrentOutputMw,
		arg.EfficiencyPercent,
		arg.FuelType,
		arg.IsActive,
		arg.CommissioningDate,
		arg.LastMaintenance,
		arg.Description,
	)
	var i HeatCenter
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LocationLat,
		&i.LocationLng,
		&i.Address,
		&i.MaxCapacityMw,
		&i.CurrentOutputMw,
		&i.EfficiencyPercent,
		&i.FuelType,
		&i.IsActive,
		&i.CommissioningDate,
		&i.LastMaintenance,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteHeatCenter = `-- name: DeleteHeatCenter :exec
DELETE FROM heat_centers
WHERE id = ?
`

func (q *Queries) DeleteHeatCenter(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteHeatCenterStmt, deleteHeatCenter, id)
	return err
}

const getHeatCenter = `-- name: GetHeatCenter :one
SELECT id, name, location_lat, location_lng, address, max_capacity_mw, current_output_mw, efficiency_percent, fuel_type, is_active, commissioning_date, last_maintenance, description, created_at, updated_at FROM heat_centers
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetHeatCenter(ctx context.Context, id int64) (HeatCenter, error) {
	row := q.queryRow(ctx, q.getHeatCenterStmt, getHeatCenter, id)
	var i HeatCenter
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LocationLat,
		&i.LocationLng,
		&i.Address,
		&i.MaxCapacityMw,
		&i.CurrentOutputMw,
		&i.EfficiencyPercent,
		&i.FuelType,
		&i.IsActive,
		&i.CommissioningDate,
		&i.LastMaintenance,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listHeatCenters = `-- name: ListHeatCenters :many
SELECT id, name, location_lat, location_lng, address, max_capacity_mw, current_output_mw, efficiency_percent, fuel_type, is_active, commissioning_date, last_maintenance, description, created_at, updated_at FROM heat_centers
ORDER BY name
LIMIT ? OFFSET ?
`

type ListHeatCentersParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListHeatCenters(ctx context.Context, arg ListHeatCentersParams) ([]HeatCenter, error) {
	rows, err := q.query(ctx, q.listHeatCentersStmt, listHeatCenters, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HeatCenter{}
	for rows.Next() {
		var i HeatCenter
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LocationLat,
			&i.LocationLng,
			&i.Address,
			&i.MaxCapacityMw,
			&i.CurrentOutputMw,
			&i.EfficiencyPercent,
			&i.FuelType,
			&i.IsActive,
			&i.CommissioningDate,
			&i.LastMaintenance,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHeatCenter = `-- name: UpdateHeatCenter :one
UPDATE heat_centers
SET
    name = COALESCE(?, name),
    location_lat = COALESCE(?, location_lat),
    location_lng = COALESCE(?, location_lng),
    address = COALESCE(?, address),
    max_capacity_mw = COALESCE(?, max_capacity_mw),
    current_output_mw = COALESCE(?, current_output_mw),
    efficiency_percent = COALESCE(?, efficiency_percent),
    fuel_type = COALESCE(?, fuel_type),
    is_active = COALESCE(?, is_active),
    commissioning_date = COALESCE(?, commissioning_date),
    last_maintenance = COALESCE(?, last_maintenance),
    description = COALESCE(?, description),
    updated_at = datetime('now')
WHERE id = ?
RETURNING id, name, location_lat, location_lng, address, max_capacity_mw, current_output_mw, efficiency_percent, fuel_type, is_active, commissioning_date, last_maintenance, description, created_at, updated_at
`

type UpdateHeatCenterParams struct {
	Name              string          `json:"name"`
	LocationLat       float64         `json:"location_lat"`
	LocationLng       float64         `json:"location_lng"`
	Address           sql.NullString  `json:"address"`
	MaxCapacityMw     float64         `json:"max_capacity_mw"`
	CurrentOutputMw   sql.NullFloat64 `json:"current_output_mw"`
	EfficiencyPercent sql.NullFloat64 `json:"efficiency_percent"`
	FuelType          sql.NullString  `json:"fuel_type"`
	IsActive          sql.NullInt64   `json:"is_active"`
	CommissioningDate sql.NullString  `json:"commissioning_date"`
	LastMaintenance   sql.NullString  `json:"last_maintenance"`
	Description       sql.NullString  `json:"description"`
	ID                int64           `json:"id"`
}

func (q *Queries) UpdateHeatCenter(ctx context.Context, arg UpdateHeatCenterParams) (HeatCenter, error) {
	row := q.queryRow(ctx, q.updateHeatCenterStmt, updateHeatCenter,
		arg.Name,
		arg.LocationLat,
		arg.LocationLng,
		arg.Address,
		arg.MaxCapacityMw,
		arg.CurrentOutputMw,
		arg.EfficiencyPercent,
		arg.FuelType,
		arg.IsActive,
		arg.CommissioningDate,
		arg.LastMaintenance,
		arg.Description,
		arg.ID,
	)
	var i HeatCenter
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LocationLat,
		&i.LocationLng,
		&i.Address,
		&i.MaxCapacityMw,
		&i.CurrentOutputMw,
		&i.EfficiencyPercent,
		&i.FuelType,
		&i.IsActive,
		&i.CommissioningDate,
		&i.LastMaintenance,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
