// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type CarbonCredit struct {
	ID                   int64          `json:"id"`
	ProjectName          string         `json:"project_name"`
	CreditType           sql.NullString `json:"credit_type"`
	PricePerTon          float64        `json:"price_per_ton"`
	AvailableTons        float64        `json:"available_tons"`
	VintageYear          sql.NullInt64  `json:"vintage_year"`
	VerificationStandard sql.NullString `json:"verification_standard"`
	Location             sql.NullString `json:"location"`
	ProjectDescription   sql.NullString `json:"project_description"`
	CreatedAt            string         `json:"created_at"`
}

type DataCenter struct {
	ID                  int64           `json:"id"`
	Name                string          `json:"name"`
	LocationLat         float64         `json:"location_lat"`
	LocationLng         float64         `json:"location_lng"`
	Address             sql.NullString  `json:"address"`
	DcType              sql.NullString  `json:"dc_type"`
	TotalItLoadKw       float64         `json:"total_it_load_kw"`
	Pue                 sql.NullFloat64 `json:"pue"`
	UtilizationPercent  sql.NullFloat64 `json:"utilization_percent"`
	CoolingType         sql.NullString  `json:"cooling_type"`
	EnergySource        sql.NullString  `json:"energy_source"`
	RenewablePercent    sql.NullFloat64 `json:"renewable_percent"`
	ElectricityCostKwh  sql.NullFloat64 `json:"electricity_cost_kwh"`
	OperatingHoursYear  sql.NullInt64   `json:"operating_hours_year"`
	HeatRecoveryEnabled sql.NullInt64   `json:"heat_recovery_enabled"`
	CreatedAt           string          `json:"created_at"`
}

type DemandSite struct {
	ID                   int64           `json:"id"`
	Name                 string          `json:"name"`
	LocationLat          float64         `json:"location_lat"`
	LocationLng          float64         `json:"location_lng"`
	Address              sql.NullString  `json:"address"`
	SiteType             sql.NullString  `json:"site_type"`
	PeakDemandMw         float64         `json:"peak_demand_mw"`
	CurrentDemandMw      sql.NullFloat64 `json:"current_demand_mw"`
	AnnualConsumptionMwh sql.NullFloat64 `json:"annual_consumption_mwh"`
	IsConnected          sql.NullInt64   `json:"is_connected"`
	ConnectionDate       sql.NullString  `json:"connection_date"`
	PriorityLevel        sql.NullInt64   `json:"priority_level"`
	FloorAreaSqm         sql.NullFloat64 `json:"floor_area_sqm"`
	BuildingAgeYears     sql.NullInt64   `json:"building_age_years"`
	InsulationRating     sql.NullString  `json:"insulation_rating"`
	Description          sql.NullString  `json:"description"`
	CreatedAt            string          `json:"created_at"`
	UpdatedAt            sql.NullString  `json:"updated_at"`
}

type DemandSiteMetric struct {
	ID                int64           `json:"id"`
	DemandSiteID      int64           `json:"demand_site_id"`
	Timestamp         string          `json:"timestamp"`
	DemandMw          float64         `json:"demand_mw"`
	SupplyTempCelsius sql.NullFloat64 `json:"supply_temp_celsius"`
	ReturnTempCelsius sql.NullFloat64 `json:"return_temp_celsius"`
	FlowRateM3Hour    sql.NullFloat64 `json:"flow_rate_m3_hour"`
	CreatedAt         string          `json:"created_at"`
}

type HeatCenter struct {
	ID                int64           `json:"id"`
	Name              string          `json:"name"`
	LocationLat       float64         `json:"location_lat"`
	LocationLng       float64         `json:"location_lng"`
	Address           sql.NullString  `json:"address"`
	MaxCapacityMw     float64         `json:"max_capacity_mw"`
	CurrentOutputMw   sql.NullFloat64 `json:"current_output_mw"`
	EfficiencyPercent sql.NullFloat64 `json:"efficiency_percent"`
	FuelType          sql.NullString  `json:"fuel_type"`
	IsActive          sql.NullInt64   `json:"is_active"`
	CommissioningDate sql.NullString  `json:"commissioning_date"`
	LastMaintenance   sql.NullString  `json:"last_maintenance"`
	Description       sql.NullString  `json:"description"`
	CreatedAt         string          `json:"created_at"`
	UpdatedAt         sql.NullString  `json:"updated_at"`
}

type HeatCenterMetric struct {
	ID                  int64           `json:"id"`
	HeatCenterID        int64           `json:"heat_center_id"`
	Timestamp           string          `json:"timestamp"`
	OutputMw            float64         `json:"output_mw"`
	EfficiencyPercent   sql.NullFloat64 `json:"efficiency_percent"`
	FuelConsumption     sql.NullFloat64 `json:"fuel_consumption"`
	OperationalCostHour sql.NullFloat64 `json:"operational_cost_hour"`
	Co2EmissionsKgHour  sql.NullFloat64 `json:"co2_emissions_kg_hour"`
	CreatedAt           string          `json:"created_at"`
}

type HeatSink struct {
	ID                      int64           `json:"id"`
	Name                    string          `json:"name"`
	LocationLat             float64         `json:"location_lat"`
	LocationLng             float64         `json:"location_lng"`
	Address                 sql.NullString  `json:"address"`
	SinkType                sql.NullString  `json:"sink_type"`
	CapacityMw              float64         `json:"capacity_mw"`
	CurrentDemandMw         sql.NullFloat64 `json:"current_demand_mw"`
	TemperatureRequirementC sql.NullFloat64 `json:"temperature_requirement_c"`
	SeasonalFactor          sql.NullFloat64 `json:"seasonal_factor"`
	ConnectionCostPerKm     sql.NullFloat64 `json:"connection_cost_per_km"`
	HeatPricePerMwh         sql.NullFloat64 `json:"heat_price_per_mwh"`
	OperatingHoursYear      sql.NullInt64   `json:"operating_hours_year"`
	CreatedAt               string          `json:"created_at"`
}

type PredictionResult struct {
	ID                    int64           `json:"id"`
	DataCenterID          int64           `json:"data_center_id"`
	CarbonCreditID        sql.NullInt64   `json:"carbon_credit_id"`
	HeatSinkID            sql.NullInt64   `json:"heat_sink_id"`
	ScenarioName          sql.NullString  `json:"scenario_name"`
	AnalysisYears         sql.NullInt64   `json:"analysis_years"`
	TotalCapex            sql.NullFloat64 `json:"total_capex"`
	AnnualOpex            sql.NullFloat64 `json:"annual_opex"`
	AnnualSavings         sql.NullFloat64 `json:"annual_savings"`
	NetPresentValue       sql.NullFloat64 `json:"net_present_value"`
	InternalRateReturn    sql.NullFloat64 `json:"internal_rate_return"`
	PaybackPeriodYears    sql.NullFloat64 `json:"payback_period_years"`
	InvestmentGrade       sql.NullString  `json:"investment_grade"`
	AnnualCo2ReductionKg  sql.NullFloat64 `json:"annual_co2_reduction_kg"`
	AnnualHeatRecoveryKwh sql.NullFloat64 `json:"annual_heat_recovery_kwh"`
	DetailedResults       sql.NullString  `json:"detailed_results"`
	CreatedAt             string          `json:"created_at"`
}

type PredictionScenario struct {
	ID             int64          `json:"id"`
	Name           string         `json:"name"`
	Description    sql.NullString `json:"description"`
	BaseParameters sql.NullString `json:"base_parameters"`
	CreatedAt      string         `json:"created_at"`
}

type Route struct {
	ID                    int64           `json:"id"`
	HeatCenterID          int64           `json:"heat_center_id"`
	DemandSiteID          int64           `json:"demand_site_id"`
	DistanceKm            float64         `json:"distance_km"`
	PipeDiameterMm        sql.NullInt64   `json:"pipe_diameter_mm"`
	MaxFlowCapacityMw     float64         `json:"max_flow_capacity_mw"`
	CurrentFlowMw         sql.NullFloat64 `json:"current_flow_mw"`
	SupplyTempCelsius     sql.NullFloat64 `json:"supply_temp_celsius"`
	ReturnTempCelsius     sql.NullFloat64 `json:"return_temp_celsius"`
	PressureBar           sql.NullFloat64 `json:"pressure_bar"`
	HeatLossPercent       sql.NullFloat64 `json:"heat_loss_percent"`
	InstallationYear      sql.NullInt64   `json:"installation_year"`
	PipeMaterial          sql.NullString  `json:"pipe_material"`
	InsulationType        sql.NullString  `json:"insulation_type"`
	Status                sql.NullString  `json:"status"`
	IsBidirectional       sql.NullInt64   `json:"is_bidirectional"`
	MaintenanceDue        sql.NullString  `json:"maintenance_due"`
	ConstructionCost      sql.NullFloat64 `json:"construction_cost"`
	AnnualMaintenanceCost sql.NullFloat64 `json:"annual_maintenance_cost"`
	CreatedAt             string          `json:"created_at"`
	UpdatedAt             sql.NullString  `json:"updated_at"`
}

type RouteMetric struct {
	ID                int64           `json:"id"`
	RouteID           int64           `json:"route_id"`
	Timestamp         string          `json:"timestamp"`
	FlowMw            float64         `json:"flow_mw"`
	SupplyTempCelsius sql.NullFloat64 `json:"supply_temp_celsius"`
	ReturnTempCelsius sql.NullFloat64 `json:"return_temp_celsius"`
	PressureBar       sql.NullFloat64 `json:"pressure_bar"`
	HeatLossMw        sql.NullFloat64 `json:"heat_loss_mw"`
	CreatedAt         string          `json:"created_at"`
}

type SystemConfig struct {
	ID          int64          `json:"id"`
	ConfigKey   string         `json:"config_key"`
	ConfigValue string         `json:"config_value"`
	ConfigType  sql.NullString `json:"config_type"`
	Description sql.NullString `json:"description"`
	IsActive    sql.NullInt64  `json:"is_active"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   sql.NullString `json:"updated_at"`
}
