// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountCarbonCredits(ctx context.Context) (int64, error)
	CountDataCenters(ctx context.Context) (int64, error)
	CountDemandSites(ctx context.Context) (int64, error)
	CountHeatCenters(ctx context.Context) (int64, error)
	CountHeatSinks(ctx context.Context) (int64, error)
	CountPredictionResults(ctx context.Context) (int64, error)
	CountRoutes(ctx context.Context) (int64, error)
	CreateCarbonCredit(ctx context.Context, arg CreateCarbonCreditParams) (CarbonCredit, error)
	CreateDataCenter(ctx context.Context, arg CreateDataCenterParams) (DataCenter, error)
	CreateDemandSite(ctx context.Context, arg CreateDemandSiteParams) (DemandSite, error)
	CreateHeatCenter(ctx context.Context, arg CreateHeatCenterParams) (HeatCenter, error)
	CreateHeatSink(ctx context.Context, arg CreateHeatSinkParams) (HeatSink, error)
	CreatePredictionResult(ctx context.Context, arg CreatePredictionResultParams) (PredictionResult, error)
	CreateRoute(ctx context.Context, arg CreateRouteParams) (Route, error)
	DeleteCarbonCredit(ctx context.Context, id int64) error
	DeleteDataCenter(ctx context.Context, id int64) error
	DeleteDemandSite(ctx context.Context, id int64) error
	DeleteHeatCenter(ctx context.Context, id int64) error
	DeleteHeatSink(ctx context.Context, id int64) error
	DeletePredictionResult(ctx context.Context, id int64) error
	DeleteRoute(ctx context.Context, id int64) error
	GetAnalyticsSummary(ctx context.Context) (GetAnalyticsSummaryRow, error)
	GetCarbonCredit(ctx context.Context, id int64) (CarbonCredit, error)
	GetDataCenter(ctx context.Context, id int64) (DataCenter, error)
	GetDemandSite(ctx context.Context, id int64) (DemandSite, error)
	GetHeatCenter(ctx context.Context, id int64) (HeatCenter, error)
	GetHeatSink(ctx context.Context, id int64) (HeatSink, error)
	GetPredictionResult(ctx context.Context, id int64) (PredictionResult, error)
	GetPredictionResultsByDataCenter(ctx context.Context, dataCenterID int64) ([]PredictionResult, error)
	GetPredictionResultsByScenario(ctx context.Context, scenarioName sql.NullString) ([]PredictionResult, error)
	GetRoute(ctx context.Context, id int64) (Route, error)
	ListCarbonCredits(ctx context.Context, arg ListCarbonCreditsParams) ([]CarbonCredit, error)
	ListDataCenters(ctx context.Context, arg ListDataCentersParams) ([]DataCenter, error)
	ListDemandSites(ctx context.Context, arg ListDemandSitesParams) ([]DemandSite, error)
	ListHeatCenters(ctx context.Context, arg ListHeatCentersParams) ([]HeatCenter, error)
	ListHeatSinks(ctx context.Context, arg ListHeatSinksParams) ([]HeatSink, error)
	ListPredictionResults(ctx context.Context, arg ListPredictionResultsParams) ([]PredictionResult, error)
	ListRoutes(ctx context.Context, arg ListRoutesParams) ([]Route, error)
	UpdateCarbonCredit(ctx context.Context, arg UpdateCarbonCreditParams) (CarbonCredit, error)
	UpdateDataCenter(ctx context.Context, arg UpdateDataCenterParams) (DataCenter, error)
	UpdateDemandSite(ctx context.Context, arg UpdateDemandSiteParams) (DemandSite, error)
	UpdateHeatCenter(ctx context.Context, arg UpdateHeatCenterParams) (HeatCenter, error)
	UpdateHeatSink(ctx context.Context, arg UpdateHeatSinkParams) (HeatSink, error)
	UpdateRoute(ctx context.Context, arg UpdateRouteParams) (Route, error)
}

var _ Querier = (*Queries)(nil)
