// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: routes.sql

package database

import (
	"context"
	"database/sql"
)

const countRoutes = `-- name: CountRoutes :one
SELECT COUNT(*) FROM routes
`

func (q *Queries) CountRoutes(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countRoutesStmt, countRoutes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRoute = `-- name: CreateRoute :one
INSERT INTO routes (
    heat_center_id,
    demand_site_id,
    distance_km,
    pipe_diameter_mm,
    max_flow_capacity_mw,
    current_flow_mw,
    supply_temp_celsius,
    return_temp_celsius,
    pressure_bar,
    heat_loss_percent,
    installation_year,
    pipe_material,
    insulation_type,
    status,
    is_bidirectional,
    maintenance_due,
    construction_cost,
    annual_maintenance_cost
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, heat_center_id, demand_site_id, distance_km, pipe_diameter_mm, max_flow_capacity_mw, current_flow_mw, supply_temp_celsius, return_temp_celsius, pressure_bar, heat_loss_percent, installation_year, pipe_material, insulation_type, status, is_bidirectional, maintenance_due, construction_cost, annual_maintenance_cost, created_at, updated_at
`

type CreateRouteParams struct {
	HeatCenterID          int64           `json:"heat_center_id"`
	DemandSiteID          int64           `json:"demand_site_id"`
	DistanceKm            float64         `json:"distance_km"`
	PipeDiameterMm        sql.NullInt64   `json:"pipe_diameter_mm"`
	MaxFlowCapacityMw     float64         `json:"max_flow_capacity_mw"`
	CurrentFlowMw         sql.NullFloat64 `json:"current_flow_mw"`
	SupplyTempCelsius     sql.NullFloat64 `json:"supply_temp_celsius"`
	ReturnTempCelsius     sql.NullFloat64 `json:"return_temp_celsius"`
	PressureBar           sql.NullFloat64 `json:"pressure_bar"`
	HeatLossPercent       sql.NullFloat64 `json:"heat_loss_percent"`
	InstallationYear      sql.NullInt64   `json:"installation_year"`
	PipeMaterial          sql.NullString  `json:"pipe_material"`
	InsulationType        sql.NullString  `json:"insulation_type"`
	Status                sql.NullString  `json:"status"`
	IsBidirectional       sql.NullInt64   `json:"is_bidirectional"`
	MaintenanceDue        sql.NullString  `json:"maintenance_due"`
	ConstructionCost      sql.NullFloat64 `json:"construction_cost"`
	AnnualMaintenanceCost sql.NullFloat64 `json:"annual_maintenance_cost"`
}

func (q *Queries) CreateRoute(ctx context.Context, arg CreateRouteParams) (Route, error) {
	row := q.queryRow(ctx, q.createRouteStmt, createRoute,
		arg.HeatCenterID,
		arg.DemandSiteID,
		arg.DistanceKm,
		arg.PipeDiameterMm,
		arg.MaxFlowCapacityMw,
		arg.CurrentFlowMw,
		arg.SupplyTempCelsius,
		arg.ReturnTempCelsius,
		arg.PressureBar,
		arg.HeatLossPercent,
		arg.InstallationYear,
		arg.PipeMaterial,
		arg.InsulationType,
		arg.Status,
		arg.IsBidirectional,
		arg.MaintenanceDue,
		arg.ConstructionCost,
		arg.AnnualMaintenanceCost,
	)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.HeatCenterID,
		&i.DemandSiteID,
		&i.DistanceKm,
		&i.PipeDiameterMm,
		&i.MaxFlowCapacityMw,
		&i.CurrentFlowMw,
		&i.SupplyTempCelsius,
		&i.ReturnTempCelsius,
		&i.PressureBar,
		&i.HeatLossPercent,
		&i.InstallationYear,
		&i.PipeMaterial,
		&i.InsulationType,
		&i.Status,
		&i.IsBidirectional,
		&i.MaintenanceDue,
		&i.ConstructionCost,
		&i.AnnualMaintenanceCost,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRoute = `-- name: DeleteRoute :exec
DELETE FROM routes
WHERE id = ?
`

func (q *Queries) DeleteRoute(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteRouteStmt, deleteRoute, id)
	return err
}

const getRoute = `-- name: GetRoute :one
SELECT id, heat_center_id, demand_site_id, distance_km, pipe_diameter_mm, max_flow_capacity_mw, current_flow_mw, supply_temp_celsius, return_temp_celsius, pressure_bar, heat_loss_percent, installation_year, pipe_material, insulation_type, status, is_bidirectional, maintenance_due, construction_cost, annual_maintenance_cost, created_at, updated_at FROM routes
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetRoute(ctx context.Context, id int64) (Route, error) {
	row := q.queryRow(ctx, q.getRouteStmt, getRoute, id)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.HeatCenterID,
		&i.DemandSiteID,
		&i.DistanceKm,
		&i.PipeDiameterMm,
		&i.MaxFlowCapacityMw,
		&i.CurrentFlowMw,
		&i.SupplyTempCelsius,
		&i.ReturnTempCelsius,
		&i.PressureBar,
		&i.HeatLossPercent,
		&i.InstallationYear,
		&i.PipeMaterial,
		&i.InsulationType,
		&i.Status,
		&i.IsBidirectional,
		&i.MaintenanceDue,
		&i.ConstructionCost,
		&i.AnnualMaintenanceCost,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRoutes = `-- name: ListRoutes :many
SELECT id, heat_center_id, demand_site_id, distance_km, pipe_diameter_mm, max_flow_capacity_mw, current_flow_mw, supply_temp_celsius, return_temp_celsius, pressure_bar, heat_loss_percent, installation_year, pipe_material, insulation_type, status, is_bidirectional, maintenance_due, construction_cost, annual_maintenance_cost, created_at, updated_at FROM routes
ORDER BY id
LIMIT ? OFFSET ?
`

type ListRoutesParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListRoutes(ctx context.Context, arg ListRoutesParams) ([]Route, error) {
	rows, err := q.query(ctx, q.listRoutesStmt, listRoutes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Route{}
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.ID,
			&i.HeatCenterID,
			&i.DemandSiteID,
			&i.DistanceKm,
			&i.PipeDiameterMm,
			&i.MaxFlowCapacityMw,
			&i.CurrentFlowMw,
			&i.SupplyTempCelsius,
			&i.ReturnTempCelsius,
			&i.PressureBar,
			&i.HeatLossPercent,
			&i.InstallationYear,
			&i.PipeMaterial,
			&i.InsulationType,
			&i.Status,
			&i.IsBidirectional,
			&i.MaintenanceDue,
			&i.ConstructionCost,
			&i.AnnualMaintenanceCost,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoute = `-- name: UpdateRoute :one
UPDATE routes
SET
    heat_center_id = COALESCE(?, heat_center_id),
    demand_site_id = COALESCE(?, demand_site_id),
    distance_km = COALESCE(?, distance_km),
    pipe_diameter_mm = COALESCE(?, pipe_diameter_mm),
    max_flow_capacity_mw = COALESCE(?, max_flow_capacity_mw),
    current_flow_mw = COALESCE(?, current_flow_mw),
    supply_temp_celsius = COALESCE(?, supply_temp_celsius),
    return_temp_celsius = COALESCE(?, return_temp_celsius),
    pressure_bar = COALESCE(?, pressure_bar),
    heat_loss_percent = COALESCE(?, heat_loss_percent),
    installation_year = COALESCE(?, installation_year),
    pipe_material = COALESCE(?, pipe_material),
    insulation_type = COALESCE(?, insulation_type),
    status = COALESCE(?, status),
    is_bidirectional = COALESCE(?, is_bidirectional),
    maintenance_due = COALESCE(?, maintenance_due),
    construction_cost = COALESCE(?, construction_cost),
    annual_maintenance_cost = COALESCE(?, annual_maintenance_cost),
    updated_at = datetime('now')
WHERE id = ?
RETURNING id, heat_center_id, demand_site_id, distance_km, pipe_diameter_mm, max_flow_capacity_mw, current_flow_mw, supply_temp_celsius, return_temp_celsius, pressure_bar, heat_loss_percent, installation_year, pipe_material, insulation_type, status, is_bidirectional, maintenance_due, construction_cost, annual_maintenance_cost, created_at, updated_at
`

type UpdateRouteParams struct {
	HeatCenterID          int64           `json:"heat_center_id"`
	DemandSiteID          int64           `json:"demand_site_id"`
	DistanceKm            float64         `json:"distance_km"`
	PipeDiameterMm        sql.NullInt64   `json:"pipe_diameter_mm"`
	MaxFlowCapacityMw     float64         `json:"max_flow_capacity_mw"`
	CurrentFlowMw         sql.NullFloat64 `json:"current_flow_mw"`
	SupplyTempCelsius     sql.NullFloat64 `json:"supply_temp_celsius"`
	ReturnTempCelsius     sql.NullFloat64 `json:"return_temp_celsius"`
	PressureBar           sql.NullFloat64 `json:"pressure_bar"`
	HeatLossPercent       sql.NullFloat64 `json:"heat_loss_percent"`
	InstallationYear      sql.NullInt64   `json:"installation_year"`
	PipeMaterial          sql.NullString  `json:"pipe_material"`
	InsulationType        sql.NullString  `json:"insulation_type"`
	Status                sql.NullString  `json:"status"`
	IsBidirectional       sql.NullInt64   `json:"is_bidirectional"`
	MaintenanceDue        sql.NullString  `json:"maintenance_due"`
	ConstructionCost      sql.NullFloat64 `json:"construction_cost"`
	AnnualMaintenanceCost sql.NullFloat64 `json:"annual_maintenance_cost"`
	ID                    int64           `json:"id"`
}

func (q *Queries) UpdateRoute(ctx context.Context, arg UpdateRouteParams) (Route, error) {
	row := q.queryRow(ctx, q.updateRouteStmt, updateRoute,
		arg.HeatCenterID,
		arg.DemandSiteID,
		arg.DistanceKm,
		arg.PipeDiameterMm,
		arg.MaxFlowCapacityMw,
		arg.CurrentFlowMw,
		arg.SupplyTempCelsius,
		arg.ReturnTempCelsius,
		arg.PressureBar,
		arg.HeatLossPercent,
		arg.InstallationYear,
		arg.PipeMaterial,
		arg.InsulationType,
		arg.Status,
		arg.IsBidirectional,
		arg.MaintenanceDue,
		arg.ConstructionCost,
		arg.AnnualMaintenanceCost,
		arg.ID,
	)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.HeatCenterID,
		&i.DemandSiteID,
		&i.DistanceKm,
		&i.PipeDiameterMm,
		&i.MaxFlowCapacityMw,
		&i.CurrentFlowMw,
		&i.SupplyTempCelsius,
		&i.ReturnTempCelsius,
		&i.PressureBar,
		&i.HeatLossPercent,
		&i.InstallationYear,
		&i.PipeMaterial,
		&i.InsulationType,
		&i.Status,
		&i.IsBidirectional,
		&i.MaintenanceDue,
		&i.ConstructionCost,
		&i.AnnualMaintenanceCost,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
