import jsPDF from 'jspdf';

interface DecisionRecord {
    recordNumber: string;
    projectName: string;
    status: string;
    complianceVerdict: string;
    jurisdiction: string;
    thermalLoadRange: string;
    investmentRange: string;
    createdAt: string;
    finalizedAt?: string;
}

export function exportRecordToPDF(record: DecisionRecord) {
    const doc = new jsPDF();

    // Header
    doc.setFontSize(20);
    doc.text('DECISION RECORD', 20, 20);

    doc.setFontSize(12);
    doc.text(`${record.recordNumber} • Official Enterprise Decision Authority`, 20, 30);

    // Horizontal line
    doc.line(20, 35, 190, 35);

    // Project Information
    doc.setFontSize(16);
    doc.text('PROJECT INFORMATION', 20, 50);

    doc.setFontSize(11);
    doc.text(`Project: ${record.projectName}`, 20, 65);
    doc.text(`Jurisdiction: ${record.jurisdiction}`, 20, 75);
    doc.text(`Thermal Load: ${record.thermalLoadRange}`, 20, 85);
    doc.text(`Investment Range: ${record.investmentRange}`, 20, 95);
    doc.text(`Created: ${new Date(record.createdAt).toLocaleDateString()}`, 20, 105);

    // Compliance Status
    doc.setFontSize(16);
    doc.text('COMPLIANCE STATUS', 20, 125);

    doc.setFontSize(11);
    doc.text(`Status: ${record.status}`, 20, 140);
    doc.text(`Compliance Verdict: ${record.complianceVerdict}`, 20, 150);

    // Footer
    doc.setFontSize(8);
    doc.text('Generated by Entropy Decision Engine', 20, 280);
    doc.text(`Export Date: ${new Date().toISOString().split('T')[0]}`, 20, 285);

    // Save the PDF
    doc.save(`${record.recordNumber}-decision-record.pdf`);
}

export function exportComplianceReportToPDF(regulations: any[], auditLogs: any[]) {
    const doc = new jsPDF();

    // Header
    doc.setFontSize(20);
    doc.text('COMPLIANCE REPORT', 20, 20);

    doc.setFontSize(12);
    doc.text('Enterprise Decision Authority • Regulatory Monitoring', 20, 30);

    // Horizontal line
    doc.line(20, 35, 190, 35);

    // Statistics
    const compliant = regulations.filter(r => r.status === 'COMPLIANT').length;
    const nonCompliant = regulations.filter(r => r.status === 'NON_COMPLIANT').length;
    const warning = regulations.filter(r => r.status === 'WARNING').length;

    doc.setFontSize(16);
    doc.text('COMPLIANCE SUMMARY', 20, 50);

    doc.setFontSize(11);
    doc.text(`Total Regulations: ${regulations.length}`, 20, 65);
    doc.text(`Compliant: ${compliant}`, 20, 75);
    doc.text(`Non-Compliant: ${nonCompliant}`, 20, 85);
    doc.text(`Warnings: ${warning}`, 20, 95);

    // Regulations List
    doc.setFontSize(16);
    doc.text('REGULATIONS STATUS', 20, 115);

    let yPos = 130;
    regulations.slice(0, 10).forEach((reg) => {
        doc.setFontSize(10);
        doc.text(`• ${reg.regulation}`, 20, yPos);
        doc.text(`  Status: ${reg.status} | ${reg.metric}`, 25, yPos + 7);
        yPos += 20;

        if (yPos > 250) {
            doc.addPage();
            yPos = 20;
        }
    });

    // Footer
    doc.setFontSize(8);
    doc.text('Generated by Entropy Decision Engine', 20, 280);
    doc.text(`Report Date: ${new Date().toISOString().split('T')[0]}`, 20, 285);

    // Save the PDF
    doc.save(`compliance-report-${new Date().toISOString().split('T')[0]}.pdf`);
}