'use client';

import React from 'react';
import { Lock } from 'lucide-react';
import { cn } from '@/lib/utils';
import { Badge } from "@/components/ui/badge";

interface RecordHeaderProps {
    recordId: string;
    projectName: string;
    jurisdiction: string;
    version: number;
    date: string;
    finalized?: boolean;
    className?: string;
}

export function RecordHeader({
    recordId,
    projectName,
    jurisdiction,
    version,
    date,
    finalized = false,
    className,
}: RecordHeaderProps) {
    return (
        <div className={cn('border-b border-white/10 pb-6 mb-8', className)}>
            {/* Finalized Banner */}
            {finalized && (
                <div className="bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 px-4 py-2 -mx-8 -mt-8 mb-6 flex items-center justify-center gap-2">
                    <Lock className="w-4 h-4" />
                    <span className="text-sm font-medium">
                        FINALIZED — This record is locked and cannot be modified
                    </span>
                </div>
            )}

            {/* Title */}
            <div className="flex flex-col md:flex-row md:items-start justify-between gap-4">
                <div>
                    <h1 className="text-3xl font-bold tracking-tight text-white mb-2">
                        HEAT REUSE DECISION & COMPLIANCE RECORD
                    </h1>
                    <p className="text-sm text-muted-foreground">
                        Official compliance document generated by Entropy Engine.
                    </p>
                </div>
                {finalized ? (
                    <Badge className="bg-emerald-500/10 text-emerald-400 border-emerald-500/20 hover:bg-emerald-500/20">
                        <Lock className="w-3 h-3 mr-1" /> LOCKED
                    </Badge>
                ) : (
                    <Badge variant="outline" className="text-muted-foreground border-white/10">
                        DRAFT
                    </Badge>
                )}
            </div>

            {/* Meta Row */}
            <div className="grid grid-cols-2 lg:grid-cols-5 gap-6 mt-6 text-sm">
                <MetaItem label="Record ID" value={recordId} fontMono />
                <MetaItem label="Project" value={projectName} />
                <MetaItem label="Jurisdiction" value={jurisdiction} />
                <MetaItem label="Version" value={`v${version}.0`} fontMono />
                <MetaItem label="Date" value={new Date(date).toLocaleDateString()} fontMono />
            </div>
        </div>
    );
}

function MetaItem({ label, value, fontMono }: { label: string, value: string | number, fontMono?: boolean }) {
    return (
        <div className="flex flex-col">
            <span className="text-muted-foreground text-xs uppercase tracking-wider mb-1">{label}</span>
            <span className={cn("text-white font-medium", fontMono && "font-mono")}>{value}</span>
        </div>
    );
}
